brcc32 ..\RES\ENGLISH\FR_DBOP.RC
brcc32 ..\RES\ENGLISH\FR_LNG1.RC
brcc32 ..\RES\ENGLISH\FR_LNG2.RC
brcc32 ..\RES\ENGLISH\FR_LNG3.RC
copy ..\RES\ENGLISH\FR_DBOP.RES .
copy ..\RES\ENGLISH\FR_LNG1.RES .
copy ..\RES\ENGLISH\FR_LNG2.RES .
copy ..\RES\ENGLISH\FR_LNG3.RES .
pause