// CodeGear C++Builder
// Copyright (c) 1995, 2020 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'DclFMXTee927.dpk' rev: 34.00 (Windows)

#ifndef Dclfmxtee927HPP
#define Dclfmxtee927HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMXTeeChartReg.hpp>
#include <FMXTee.Bind.DBLinks.hpp>
#include <FMXTee.Bind.Editors.hpp>
#include <BindCompFMXTeeReg.hpp>
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <IDEMessages.hpp>	// (designide)
#include <Vcl.CaptionedDockTree.hpp>	// (vcl)
#include <Vcl.DockTabSet.hpp>	// (vcl)
#include <Vcl.Grids.hpp>	// (vcl)
#include <Vcl.CategoryButtons.hpp>	// (vcl)
#include <Vcl.ButtonGroup.hpp>	// (vcl)
#include <Vcl.SysStyles.hpp>	// (vcl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Vcl.Direct2D.hpp>	// (vcl)
#include <Vcl.Styles.hpp>	// (vcl)
#include <BrandingAPI.hpp>	// (designide)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <PercentageDockTree.hpp>	// (designide)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.ExtActns.hpp>	// (vcl)
#include <Vcl.ActnMenus.hpp>	// (vclactnband)
#include <Vcl.ActnMan.hpp>	// (vclactnband)
#include <Vcl.PlatformDefaultStyleActnCtrls.hpp>	// (vclactnband)
#include <BaseDock.hpp>	// (designide)
#include <DeskUtil.hpp>	// (designide)
#include <DeskForm.hpp>	// (designide)
#include <DockForm.hpp>	// (designide)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <ToolsAPI.hpp>	// (designide)
#include <Proxies.hpp>	// (designide)
#include <DesignEditors.hpp>	// (designide)
#include <PropertyCategories.hpp>	// (designide)
#include <System.Devices.hpp>	// (rtl)
#include <Vcl.AxCtrls.hpp>	// (vcl)
#include <Vcl.AppEvnts.hpp>	// (vcl)
#include <TreeIntf.hpp>	// (designide)
#include <TopLevels.hpp>	// (designide)
#include <StFilSys.hpp>	// (designide)
#include <IDEHelp.hpp>	// (designide)
#include <ComponentDesigner.hpp>	// (designide)
#include <VCLEditors.hpp>	// (designide)
#include <ToolWnds.hpp>	// (designide)
#include <ColnEdit.hpp>	// (designide)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <FMX.ImgList.hpp>	// (fmx)
#include <FMX.DialogService.Sync.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <FMX.DialogService.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <FMX.Helpers.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.Objects.hpp>	// (fmx)
#include <FMX.Canvas.GDIP.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Controls.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Switch.Win.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.Win.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.DialogHelper.hpp>	// (fmx)
#include <FMX.Dialogs.Win.hpp>	// (fmx)
#include <FMX.Canvas.D2D.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.Context.DX9.hpp>	// (fmx)
#include <FMX.Context.DX11.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <System.Win.InternetExplorer.hpp>	// (rtl)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.Platform.Win.hpp>	// (fmx)
#include <FMX.Gestures.Win.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Clipboard.Win.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <FMX.Colors.hpp>	// (fmx)
#include <FMXTee.Html.hpp>	// (FMXTee927)
#include <FMXTee.Constants.hpp>	// (FMXTee927)
#include <FMXTee.Canvas.hpp>	// (FMXTee927)
#include <FMXTee.Procs.hpp>	// (FMXTee927)
#include <FMXTee.Engine.hpp>	// (FMXTee927)
#include <FMXTee.Chart.hpp>	// (FMXTee927)
#include <FMX.Controls3D.hpp>	// (fmx)
#include <FMX.MaterialSources.hpp>	// (fmx)
#include <FMX.Import.hpp>	// (fmx)
#include <FMX.Objects3D.hpp>	// (fmx)
#include <FMX.Layers3D.hpp>	// (fmx)
#include <FMXTee.Chart3D.hpp>	// (FMXTee927)
#include <FMXTee.Series.Spline.hpp>	// (FMXTee927)
#include <FMXTee.Animations.hpp>	// (FMXTee927)
#include <Data.SqlTimSt.hpp>	// (dbrtl)
#include <Data.FmtBcd.hpp>	// (dbrtl)
#include <Data.DB.hpp>	// (dbrtl)
#include <FMXTee.Chart.Crosstab.hpp>	// (FMXTeeDB927)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.ScrollBox.Win.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.Memo.Style.New.hpp>	// (fmx)
#include <FMX.Memo.Win.hpp>	// (fmx)
#include <FMX.Memo.hpp>	// (fmx)
#include <FMX.TreeView.hpp>	// (fmx)
#include <FMX.TabControl.hpp>	// (fmx)
#include <FMXTee.Tools.Gallery.hpp>	// (FmxTeeUI927)
#include <FMX.EditBox.Style.hpp>	// (fmx)
#include <FMX.SpinBox.Style.hpp>	// (fmx)
#include <FMX.SpinBox.hpp>	// (fmx)
#include <FMXTee.Chart.GalleryPanel.hpp>	// (FmxTeeUI927)
#include <FMXTee.Chart.ListBox.hpp>	// (FmxTeeUI927)
#include <FMX.ComboEdit.Style.hpp>	// (fmx)
#include <FMX.ComboEdit.hpp>	// (fmx)
#include <FMXTee.Editor.Export.Bitmap.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Export.hpp>	// (FmxTeeUI927)
#include <FMX.NumberBox.Style.hpp>	// (fmx)
#include <FMX.NumberBox.hpp>	// (fmx)
#include <FMXTee.Chart.Functions.hpp>	// (FMXTee927)
#include <FMXTee.Editor.DBSource.hpp>	// (FMXTeeDB927)
#include <FMXTee.Editor.DBSummary.hpp>	// (FMXTeeDB927)
#include <FMXTee.Editor.DBChart.hpp>	// (FMXTeeDB927)
#include <FMXTee.Editor.CrossTab.hpp>	// (FMXTeeDB927)
#include <FMX.Viewport3D.hpp>	// (fmx)
#include <FMX.ComboTrackBar.Style.hpp>	// (fmx)
#include <FMX.ComboTrackBar.hpp>	// (fmx)
#include <FMX.Grid.hpp>	// (fmx)
#include <FMX.Grid.Style.hpp>	// (fmx)
#include <FMXTee.Chart.Grid.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Pointer.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Functions.Period.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Functions.Average.hpp>	// (FmxTeeUI927)
#include <FMXTee.Filters.hpp>	// (FmxTeeUI927)
#include <FMXTee.Animate.hpp>	// (FmxTeeUI927)
#include <FMXTee.Animations.Tools.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Animation.hpp>	// (FmxTeeUI927)
#include <FMXTee.Animations.Gallery.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Arrow.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Arrow.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Bubble.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Bubble.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Gantt.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Gantt.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Shape.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Shape.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Area.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.CustomBar.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Custom.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.FastLine.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Pie.hpp>	// (FmxTeeUI927)
#include <System.Bindings.Search.hpp>	// (bindengine)
#include <System.Bindings.Evaluator.hpp>	// (bindengine)
#include <System.Bindings.EvalSys.hpp>	// (bindengine)
#include <System.Bindings.Graph.hpp>	// (bindengine)
#include <System.Bindings.Factories.hpp>	// (bindengine)
#include <System.Bindings.Outputs.hpp>	// (bindengine)
#include <System.Bindings.Methods.hpp>	// (bindengine)
#include <Data.Bind.Grid.hpp>	// (bindcomp)
#include <Data.Bind.Components.hpp>	// (bindcomp)
#include <Data.Bind.ObjectScope.hpp>	// (bindcomp)
#include <Data.Bind.DBScope.hpp>	// (bindcomp)
#include <Data.Bind.DBLinks.hpp>	// (bindcomp)
#include <Fmx.Bind.DBLinks.hpp>	// (Bindcompfmx)
// PRG_EXT: .bpl
// BPI_DIR: C:\tcroot\TeeChartVCL\Sources9\Compiled\Delphi27.win32\Lib\Obj
// OBJ_DIR: C:\tcroot\TeeChartVCL\Sources9\Compiled\Delphi27.win32\Lib\Obj
// OBJ_EXT: .obj

//-- user supplied -----------------------------------------------------------

namespace Dclfmxtee927
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Dclfmxtee927 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_DCLFMXTEE927)
using namespace Dclfmxtee927;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Dclfmxtee927HPP
