// CodeGear C++Builder
// Copyright (c) 1995, 2020 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'FMXTeeImport927.dpk' rev: 34.00 (Windows)

#ifndef Fmxteeimport927HPP
#define Fmxteeimport927HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FMXTee.Import.hpp>
#include <FMXTee.Editor.Import.hpp>
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <System.Devices.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <FMX.Utils.hpp>	// (fmx)
#include <FMX.Text.hpp>	// (fmx)
#include <FMX.TextLayout.hpp>	// (fmx)
#include <FMX.Graphics.hpp>	// (fmx)
#include <FMX.BehaviorManager.hpp>	// (fmx)
#include <FMX.Styles.hpp>	// (fmx)
#include <FMX.Types3D.hpp>	// (fmx)
#include <FMX.Filter.hpp>	// (fmx)
#include <FMX.Filter.Custom.hpp>	// (fmx)
#include <FMX.Effects.hpp>	// (fmx)
#include <System.SyncObjs.hpp>	// (rtl)
#include <FMX.MultiResBitmap.hpp>	// (fmx)
#include <FMX.Ani.hpp>	// (fmx)
#include <FMX.ImgList.hpp>	// (fmx)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <FMX.DialogService.Sync.hpp>	// (fmx)
#include <FMX.Dialogs.hpp>	// (fmx)
#include <FMX.DialogService.hpp>	// (fmx)
#include <FMX.Menus.hpp>	// (fmx)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <FMX.Helpers.Win.hpp>	// (fmx)
#include <FMX.FontGlyphs.hpp>	// (fmx)
#include <FMX.Objects.hpp>	// (fmx)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <FMX.Canvas.GDIP.hpp>	// (fmx)
#include <FMX.Printer.hpp>	// (fmx)
#include <FMX.Presentation.Factory.hpp>	// (fmx)
#include <FMX.Controls.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.hpp>	// (fmx)
#include <FMX.Presentation.Win.Style.hpp>	// (fmx)
#include <FMX.Controls.Presentation.hpp>	// (fmx)
#include <FMX.Styles.Objects.hpp>	// (fmx)
#include <FMX.Styles.Switch.hpp>	// (fmx)
#include <FMX.Switch.Style.hpp>	// (fmx)
#include <FMX.Switch.Win.hpp>	// (fmx)
#include <FMX.StdCtrls.hpp>	// (fmx)
#include <FMX.InertialMovement.hpp>	// (fmx)
#include <FMX.Layouts.hpp>	// (fmx)
#include <FMX.MagnifierGlass.hpp>	// (fmx)
#include <FMX.Edit.Style.hpp>	// (fmx)
#include <FMX.Edit.Win.hpp>	// (fmx)
#include <FMX.Edit.hpp>	// (fmx)
#include <FMX.DialogHelper.hpp>	// (fmx)
#include <FMX.Dialogs.Win.hpp>	// (fmx)
#include <FMX.Canvas.D2D.hpp>	// (fmx)
#include <FMX.Canvas.GPU.Helpers.hpp>	// (fmx)
#include <FMX.TextLayout.GPU.hpp>	// (fmx)
#include <FMX.Canvas.GPU.hpp>	// (fmx)
#include <FMX.Context.DX9.hpp>	// (fmx)
#include <FMX.Context.DX11.hpp>	// (fmx)
#include <FMX.ListBox.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.Types.hpp>	// (fmx)
#include <FMX.DateTimeCtrls.hpp>	// (fmx)
#include <FMX.Calendar.Style.hpp>	// (fmx)
#include <FMX.Calendar.hpp>	// (fmx)
#include <FMX.Pickers.hpp>	// (fmx)
#include <FMX.ExtCtrls.hpp>	// (fmx)
#include <System.Win.InternetExplorer.hpp>	// (rtl)
#include <FMX.WebBrowser.hpp>	// (fmx)
#include <FMX.Platform.Win.hpp>	// (fmx)
#include <FMX.Gestures.Win.hpp>	// (fmx)
#include <FMX.Gestures.hpp>	// (fmx)
#include <FMX.Controls.hpp>	// (fmx)
#include <FMX.Header.hpp>	// (fmx)
#include <FMX.Forms.hpp>	// (fmx)
#include <FMX.Clipboard.Win.hpp>	// (fmx)
#include <FMX.Platform.hpp>	// (fmx)
#include <FMX.Types.hpp>	// (fmx)
#include <FMX.Colors.hpp>	// (fmx)
#include <FMXTee.Html.hpp>	// (FMXTee927)
#include <FMXTee.Constants.hpp>	// (FMXTee927)
#include <FMXTee.Canvas.hpp>	// (FMXTee927)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <FMXTee.Procs.hpp>	// (FMXTee927)
#include <FMXTee.Engine.hpp>	// (FMXTee927)
#include <FMXTee.Chart.hpp>	// (FMXTee927)
#include <FMXTee.Series.Spline.hpp>	// (FMXTee927)
#include <FMXTee.Series.Bubble.hpp>	// (FMXTee927)
#include <FMXTee.ProConstants.hpp>	// (FMXTeePro927)
#include <FMXTee.Series.Surface.hpp>	// (FMXTeePro927)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <System.Zip.hpp>	// (rtl)
#include <FMXTee.Series.Map.hpp>	// (FMXTeePro927)
#include <Data.SqlTimSt.hpp>	// (dbrtl)
#include <Data.FmtBcd.hpp>	// (dbrtl)
#include <Data.DB.hpp>	// (dbrtl)
#include <FMXTee.Tools.hpp>	// (FMXTeePro927)
#include <FMXTee.Series.World.hpp>	// (FMXTeePro927)
#include <FMXTee.Series.OHLC.hpp>	// (FMXTeePro927)
#include <FMXTee.Series.Candle.hpp>	// (FMXTeePro927)
#include <FMX.ScrollBox.Style.hpp>	// (fmx)
#include <FMX.ScrollBox.Win.hpp>	// (fmx)
#include <FMX.ScrollBox.hpp>	// (fmx)
#include <FMX.Grid.hpp>	// (fmx)
#include <System.JSON.hpp>	// (rtl)
#include <System.Net.Mime.hpp>	// (rtl)
#include <System.Threading.hpp>	// (rtl)
#include <System.NetEncoding.hpp>	// (rtl)
#include <System.Net.URLClient.hpp>	// (rtl)
#include <System.Net.HttpClient.Win.hpp>	// (rtl)
#include <System.JSON.Types.hpp>	// (rtl)
#include <System.JSON.Utils.hpp>	// (rtl)
#include <System.JSON.Readers.hpp>	// (rtl)
#include <System.JSON.Writers.hpp>	// (rtl)
#include <System.Bindings.Search.hpp>	// (bindengine)
#include <System.Bindings.Evaluator.hpp>	// (bindengine)
#include <System.Bindings.EvalSys.hpp>	// (bindengine)
#include <System.Bindings.Graph.hpp>	// (bindengine)
#include <System.Bindings.Factories.hpp>	// (bindengine)
#include <System.Bindings.Outputs.hpp>	// (bindengine)
#include <System.Bindings.Methods.hpp>	// (bindengine)
#include <Data.Bind.Grid.hpp>	// (bindcomp)
#include <Data.Bind.Components.hpp>	// (bindcomp)
#include <Data.Bind.ObjectScope.hpp>	// (bindcomp)
#include <Data.Bind.JSON.hpp>	// (bindcomp)
#include <REST.JsonReflect.hpp>	// (RESTComponents)
#include <Xml.XMLSchema.hpp>	// (xmlrtl)
#include <FMXTee.Themes.hpp>	// (FMXTeePro927)
#include <FMXTee.Tools.SubChart.hpp>	// (FMXTeePro927)
#include <FMXTee.Tools.ScrollPager.hpp>	// (FMXTeePro927)
#include <FMX.Memo.Style.New.hpp>	// (fmx)
#include <FMX.Memo.Win.hpp>	// (fmx)
#include <FMX.Memo.hpp>	// (fmx)
#include <IdGlobal.hpp>	// (IndySystem)
#include <IdWinsock2.hpp>	// (IndySystem)
#include <IdWship6.hpp>	// (IndySystem)
#include <IdIDN.hpp>	// (IndySystem)
#include <IdStackWindows.hpp>	// (IndySystem)
#include <IdStack.hpp>	// (IndySystem)
#include <IdGlobalProtocols.hpp>	// (IndyProtocols)
#include <IdCoderMIME.hpp>	// (IndyProtocols)
#include <IdAuthentication.hpp>	// (IndyProtocols)
#include <IdHTTPHeaderInfo.hpp>	// (IndyProtocols)
#include <IdComponent.hpp>	// (IndySystem)
#include <IdIOHandler.hpp>	// (IndyCore)
#include <IdIOHandlerStack.hpp>	// (IndyCore)
#include <IdThread.hpp>	// (IndyCore)
#include <IdSSL.hpp>	// (IndyProtocols)
#include <IdHeaderCoderBase.hpp>	// (IndyProtocols)
#include <IdHeaderCoderPlain.hpp>	// (IndyProtocols)
#include <IdHeaderCoder2022JP.hpp>	// (IndyProtocols)
#include <IdHeaderCoderIndy.hpp>	// (IndyProtocols)
#include <IdFIPS.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSLHeaders.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSL.hpp>	// (IndyProtocols)
#include <IdAuthenticationNTLM.hpp>	// (IndyProtocols)
#include <IdAuthenticationSSPI.hpp>	// (IndyProtocols)
#include <IdAuthenticationDigest.hpp>	// (IndyProtocols)
#include <IdFTPListParseBase.hpp>	// (IndyProtocols)
#include <Datasnap.DSIntf.hpp>	// (dsnap)
#include <FMX.ComboEdit.Style.hpp>	// (fmx)
#include <FMX.ComboEdit.hpp>	// (fmx)
#include <FMX.TabControl.hpp>	// (fmx)
#include <FMX.TreeView.hpp>	// (fmx)
#include <FMX.EditBox.Style.hpp>	// (fmx)
#include <FMX.SpinBox.Style.hpp>	// (fmx)
#include <FMX.SpinBox.hpp>	// (fmx)
#include <FMXTee.Chart.GalleryPanel.hpp>	// (FmxTeeUI927)
#include <FMX.ComboTrackBar.Style.hpp>	// (fmx)
#include <FMX.ComboTrackBar.hpp>	// (fmx)
#include <FMXTee.Chart.Functions.hpp>	// (FMXTee927)
#include <FMXTee.Chart.ListBox.hpp>	// (FmxTeeUI927)
#include <FMX.NumberBox.Style.hpp>	// (fmx)
#include <FMX.NumberBox.hpp>	// (fmx)
#include <FMX.Grid.Style.hpp>	// (fmx)
#include <FMXTee.Chart.Grid.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Pointer.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Functions.Period.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Functions.Average.hpp>	// (FmxTeeUI927)
#include <FMX.Controls3D.hpp>	// (fmx)
#include <FMXTee.Editor.Export.Bitmap.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Export.hpp>	// (FmxTeeUI927)
#include <FMXTee.Tools.Gallery.hpp>	// (FmxTeeUI927)
#include <FMXTee.Filters.hpp>	// (FmxTeeUI927)
#include <FMXTee.Animate.hpp>	// (FmxTeeUI927)
#include <FMXTee.Animations.Tools.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Animation.hpp>	// (FmxTeeUI927)
#include <FMXTee.Animations.Gallery.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Arrow.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Arrow.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Bubble.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Gantt.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Gantt.hpp>	// (FmxTeeUI927)
#include <FMXTee.Series.Shape.hpp>	// (FMXTee927)
#include <FMXTee.Editor.Series.Shape.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Area.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.CustomBar.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Custom.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.FastLine.hpp>	// (FmxTeeUI927)
#include <FMXTee.Editor.Series.Pie.hpp>	// (FmxTeeUI927)
// PRG_EXT: .bpl
// BPI_DIR: C:\tcroot\TeeChartVCL\Sources9\Compiled\Delphi27.win32\Lib\Obj
// OBJ_DIR: C:\tcroot\TeeChartVCL\Sources9\Compiled\Delphi27.win32\Lib\Obj
// OBJ_EXT: .obj

//-- user supplied -----------------------------------------------------------

namespace Fmxteeimport927
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Fmxteeimport927 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_FMXTEEIMPORT927)
using namespace Fmxteeimport927;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Fmxteeimport927HPP
