// CodeGear C++Builder
// Copyright (c) 1995, 2020 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'TeeImport927.dpk' rev: 34.00 (Windows)

#ifndef Teeimport927HPP
#define Teeimport927HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <VCLTee.TeeImport.hpp>
#include <VCLTee.TeeImportEditor.hpp>
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Vcl.Grids.hpp>	// (vcl)
#include <VCLTee.TeeHtml.hpp>	// (Tee927)
#include <VCLTee.TeeConst.hpp>	// (Tee927)
#include <VCLTee.TeCanvas.hpp>	// (Tee927)
#include <VCLTee.TeeFilters.hpp>	// (Tee927)
#include <VCLTee.TeeProcs.hpp>	// (Tee927)
#include <VCLTee.TeEngine.hpp>	// (Tee927)
#include <VCLTee.Chart.hpp>	// (Tee927)
#include <VCLTee.TeeStore.hpp>	// (Tee927)
#include <VCLTee.TeeSpline.hpp>	// (Tee927)
#include <VCLTee.BubbleCh.hpp>	// (Tee927)
#include <VCLTee.TeeProCo.hpp>	// (TeePro927)
#include <VCLTee.TeeSurfa.hpp>	// (TeePro927)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <System.Zip.hpp>	// (rtl)
#include <VCLTee.TeeMapSeries.hpp>	// (TeePro927)
#include <Data.SqlTimSt.hpp>	// (dbrtl)
#include <Data.FmtBcd.hpp>	// (dbrtl)
#include <Data.DB.hpp>	// (dbrtl)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <VCLTee.TeeEmfOptions.hpp>	// (TeeUI927)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.CheckLst.hpp>	// (vclx)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <VCLTee.TeeGDIPlus.hpp>	// (Tee927)
#include <VCLTee.TeeGalleryPanel.hpp>	// (TeeUI927)
#include <Vcl.Imaging.jpeg.hpp>	// (vclimg)
#include <VCLTee.TeeBmpOptions.hpp>	// (TeeUI927)
#include <VCLTee.TeeExport.hpp>	// (TeeUI927)
#include <VCLTee.TeeTools.hpp>	// (TeePro927)
#include <VCLTee.TeeWorldSeries.hpp>	// (TeeWorld927)
#include <VCLTee.OHLChart.hpp>	// (TeePro927)
#include <VCLTee.CandleCh.hpp>	// (TeePro927)
#include <System.JSON.hpp>	// (rtl)
#include <System.Net.Mime.hpp>	// (rtl)
#include <System.Threading.hpp>	// (rtl)
#include <System.NetEncoding.hpp>	// (rtl)
#include <System.Net.URLClient.hpp>	// (rtl)
#include <System.Net.HttpClient.Win.hpp>	// (rtl)
#include <System.JSON.Types.hpp>	// (rtl)
#include <System.JSON.Utils.hpp>	// (rtl)
#include <System.JSON.Readers.hpp>	// (rtl)
#include <System.JSON.Writers.hpp>	// (rtl)
#include <System.Bindings.Search.hpp>	// (bindengine)
#include <System.Bindings.Evaluator.hpp>	// (bindengine)
#include <System.Bindings.EvalSys.hpp>	// (bindengine)
#include <System.Bindings.Graph.hpp>	// (bindengine)
#include <System.Bindings.Factories.hpp>	// (bindengine)
#include <System.Bindings.Outputs.hpp>	// (bindengine)
#include <System.Bindings.Methods.hpp>	// (bindengine)
#include <Data.Bind.Grid.hpp>	// (bindcomp)
#include <Data.Bind.Components.hpp>	// (bindcomp)
#include <Data.Bind.ObjectScope.hpp>	// (bindcomp)
#include <Data.Bind.JSON.hpp>	// (bindcomp)
#include <REST.JsonReflect.hpp>	// (RESTComponents)
#include <Xml.XMLSchema.hpp>	// (xmlrtl)
#include <VCLTee.TeeThemes.hpp>	// (TeePro927)
#include <VCLTee.TeeSubChart.hpp>	// (TeePro927)
#include <VCLTee.TeeScrollPagerTool.hpp>	// (TeePro927)
#include <IdGlobal.hpp>	// (IndySystem)
#include <IdWinsock2.hpp>	// (IndySystem)
#include <IdWship6.hpp>	// (IndySystem)
#include <IdIDN.hpp>	// (IndySystem)
#include <IdStackWindows.hpp>	// (IndySystem)
#include <IdStack.hpp>	// (IndySystem)
#include <IdGlobalProtocols.hpp>	// (IndyProtocols)
#include <IdCoderMIME.hpp>	// (IndyProtocols)
#include <IdAuthentication.hpp>	// (IndyProtocols)
#include <IdHTTPHeaderInfo.hpp>	// (IndyProtocols)
#include <IdComponent.hpp>	// (IndySystem)
#include <IdIOHandler.hpp>	// (IndyCore)
#include <IdIOHandlerStack.hpp>	// (IndyCore)
#include <IdThread.hpp>	// (IndyCore)
#include <IdSSL.hpp>	// (IndyProtocols)
#include <IdHeaderCoderBase.hpp>	// (IndyProtocols)
#include <IdHeaderCoderPlain.hpp>	// (IndyProtocols)
#include <IdHeaderCoder2022JP.hpp>	// (IndyProtocols)
#include <IdHeaderCoderIndy.hpp>	// (IndyProtocols)
#include <IdFIPS.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSLHeaders.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSL.hpp>	// (IndyProtocols)
#include <IdAuthenticationNTLM.hpp>	// (IndyProtocols)
#include <IdAuthenticationSSPI.hpp>	// (IndyProtocols)
#include <IdAuthenticationDigest.hpp>	// (IndyProtocols)
#include <IdFTPListParseBase.hpp>	// (IndyProtocols)
#include <Datasnap.DSIntf.hpp>	// (dsnap)
#include <VCLTee.TeeTextShapeEditor.hpp>	// (TeeUI927)
#include <VCLTee.TeeFunci.hpp>	// (Tee927)
#include <VCLTee.TeeGally.hpp>	// (TeeUI927)
#include <VCLTee.TeeBaseFuncEdit.hpp>	// (TeeUI927)
#include <VCLTee.TeeEdiPeri.hpp>	// (TeeUI927)
#include <VCLTee.TeePoEdi.hpp>	// (TeeUI927)
#include <VCLTee.TeeToolsGallery.hpp>	// (TeeUI927)
#include <VCLTee.TeeEditTools.hpp>	// (TeeUI927)
#include <VCLTee.TeeAnimate.hpp>	// (TeeUI927)
#include <VCLTee.TeeAnimations.hpp>	// (TeeUI927)
#include <VCLTee.TeeAnimationEditor.hpp>	// (TeeUI927)
#include <VCLTee.TeeAnimationEditors.hpp>	// (TeeUI927)
#include <VCLTee.TeeAnimationsGallery.hpp>	// (TeeUI927)
#include <VCLTee.TeeAbout.hpp>	// (Tee927)
#include <VCLTee.TeeEditCha.hpp>	// (TeeUI927)
// PRG_EXT: .bpl
// BPI_DIR: C:\tcroot\TeeChartVCL\Sources9\Compiled\Delphi27.win32\Lib\Obj
// OBJ_DIR: C:\tcroot\TeeChartVCL\Sources9\Compiled\Delphi27.win32\Lib\Obj
// OBJ_EXT: .obj

//-- user supplied -----------------------------------------------------------

namespace Teeimport927
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Teeimport927 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_TEEIMPORT927)
using namespace Teeimport927;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Teeimport927HPP
