// CodeGear C++Builder
// Copyright (c) 1995, 2016 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'dcllmdtoolsdb.dpk' rev: 31.00 (Windows)

#ifndef DcllmdtoolsdbHPP
#define DcllmdtoolsdbHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <LMD_RegMainDB.hpp>
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <System.Actions.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <Data.SqlTimSt.hpp>	// (dbrtl)
#include <Data.FmtBcd.hpp>	// (dbrtl)
#include <Data.DB.hpp>	// (dbrtl)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.DBLogDlg.hpp>	// (vcldb)
#include <Vcl.DBPWDlg.hpp>	// (vcldb)
#include <Vcl.DBCtrls.hpp>	// (vcldb)
#include <LMDUnicode.hpp>	// (lmdrtl)
#include <LMDIniCtrl.hpp>	// (lmdrtl)
#include <LMDShUtils.hpp>	// (lmdrtl)
#include <LMDClass.hpp>	// (lmdrtl)
#include <LMDTypes.hpp>	// (lmdrtl)
#include <LMDZCompressUnit.hpp>	// (lmdrtl)
#include <LMDSysIn.hpp>	// (lmdrtl)
#include <LMDThemes.hpp>	// (lmdrtrtlx)
#include <LMDButtonBase.hpp>	// (lmdrtrtlx)
#include <LMDUtils.hpp>	// (lmdrtl)
#include <LMDGraphUtils.hpp>	// (lmdrtrtlx)
#include <LMDPNGImage.hpp>	// (lmdrtrtlx)
#include <LMDCont.hpp>	// (lmdrtrtlx)
#include <LMDLED.hpp>	// (lmdrttools)
#include <LMDCFCSettingObject.hpp>	// (lmdrtrtlx)
#include <LMDCFCStateObject.hpp>	// (lmdrtrtlx)
#include <LMDStyleMan.hpp>	// (lmdrtrtlx)
#include <LMDCustomStatusBar.hpp>	// (lmdrtrtlx)
#include <LMDHookComponent.hpp>	// (lmdrtrtlx)
#include <LMDHTMLUnit.hpp>	// (lmdrtrtlx)
#include <LMDGlyph.hpp>	// (lmdrtrtlx)
#include <LMDDateUtils.hpp>	// (lmdrtl)
#include <LMDTimeFormat.hpp>	// (lmdrtcore)
#include <LMDComboBoxExt.hpp>	// (lmdrtcore)
#include <LMDDateTime.hpp>	// (lmdrtl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <pLMDCst.hpp>	// (dcllmdrtl)
#include <pLMDCPGetBase.hpp>	// (dcllmdrtl)
#include <Vcl.AxCtrls.hpp>	// (vcl)
#include <pLMDCommon.hpp>	// (dcllmdrtl)
#include <IDEMessages.hpp>	// (designide)
#include <Vcl.CaptionedDockTree.hpp>	// (vcl)
#include <Vcl.DockTabSet.hpp>	// (vcl)
#include <PercentageDockTree.hpp>	// (designide)
#include <BrandingAPI.hpp>	// (designide)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.ExtActns.hpp>	// (vcl)
#include <Vcl.ActnMenus.hpp>	// (vclactnband)
#include <Vcl.ActnMan.hpp>	// (vclactnband)
#include <Vcl.PlatformDefaultStyleActnCtrls.hpp>	// (vclactnband)
#include <BaseDock.hpp>	// (designide)
#include <DeskUtil.hpp>	// (designide)
#include <DeskForm.hpp>	// (designide)
#include <DockForm.hpp>	// (designide)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <ToolsAPI.hpp>	// (designide)
#include <Proxies.hpp>	// (designide)
#include <DesignEditors.hpp>	// (designide)
#include <System.Devices.hpp>	// (rtl)
#include <Vcl.AppEvnts.hpp>	// (vcl)
#include <TreeIntf.hpp>	// (designide)
#include <TopLevels.hpp>	// (designide)
#include <StFilSys.hpp>	// (designide)
#include <IDEHelp.hpp>	// (designide)
#include <ComponentDesigner.hpp>	// (designide)
#include <VCLEditors.hpp>	// (designide)
#include <LMDSplt.hpp>	// (lmdrtcore)
#include <LMDPageControl.hpp>	// (lmdrtcore)
#include <LMDDwmApi.hpp>	// (lmdrtrtlx)
#include <pLMDPeCore.hpp>	// (dcllmdcore)
#include <ToolWnds.hpp>	// (designide)
#include <ColnEdit.hpp>	// (designide)
#include <pLMDGlobalEditors.hpp>	// (dcllmdrtl)
#include <pLMDCEBase.hpp>	// (dcllmdrtlx)
#include <LMDCustomShapeHint.hpp>	// (lmdrtcore)
#include <Vcl.Imaging.pngimage.hpp>	// (vclimg)
#include <pLMDActionsData.hpp>	// (dcllmdrtlx)
#include <LMDFormPersistent.hpp>	// (lmdrtrtlx)
#include <LMDExtDialogs.hpp>	// (lmdrtrtlx)
#include <pLMDStdListEditorDlg.hpp>	// (dcllmdrtlx)
#include <pLMDExtImageListEditorDlg.hpp>	// (dcllmdrtlx)
#include <pLMDDsgnCPGetX.hpp>	// (dcllmdrtlx)
#include <LMDRegExpr.hpp>	// (lmdrtl)
#include <pLMDToolBarEditorDlg.hpp>	// (dcllmdcore)
#include <pLMDCECore.hpp>	// (dcllmdcore)
#include <pLMDOIEnh.hpp>	// (dcllmdrtl)
#include <Vcl.Grids.hpp>	// (vcl)
#include <Vcl.DBGrids.hpp>	// (vcldb)
#include <DrpCtrls.hpp>	// (dcldb)
#include <DSDefine.hpp>	// (dcldb)
#include <DSDesign.hpp>	// (dcldb)

//-- user supplied -----------------------------------------------------------

namespace Dcllmdtoolsdb
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Dcllmdtoolsdb */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_DCLLMDTOOLSDB)
using namespace Dcllmdtoolsdb;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// DcllmdtoolsdbHPP
