unit LMDRTFLookupTable;
{$I LMDCmps.inc}

{###############################################################################

LMD VCL Series 2016
© by LMD Innovative
-------------------

For support or information contact us at:

email              : mail@lmdsupport.com
WWW                : http://www.lmdinnovative.com
SupportSite        : http://www.lmdsupport.com
Wiki               : http://wiki.lmd.de
Fax                : ++49 6131 4984372

This code is for reference purposes only and may not be copied
or distributed in any format electronic or otherwise except one
copy for backup purposes.

No Component Kit or Component individually or in a collection,
subclassed or otherwise from the code in this unit, or associated
.pas, .dfm, .dcu, .ocx, .dll or ActiveX files may be sold or
distributed without express permission from LMD Innovative.

For further license information please refer to the associated
license html file in \info folder.

################################################################################

LMDRTFLookupTable unit (VO)
---------------------------

RTF lookup table support 

ToDo:

Changes
-------
Release 8.0 (October 2006)
 - Initial Release

###############################################################################}

interface

const
  tocEOF = 0;
  tocWAIT = 1;
  tocOPENGROUP = 2;
  tocCLOSEGROUP = 3;
  tocPLAINTEXT = 4;
  tocRTF = 5;
  tocDEFF = 6;
  tocANSI = 7;
  tocMAC = 8;
  tocPC = 9;
  tocPCA = 10;
  tocANSICPG = 11;
  tocUPR = 12;
  tocUD = 13;
  tocU = 14;
  tocUC = 15;
  tocUCL = 16;
  tocBKMKSTART = 17;
  tocFONTTBL = 18;
  tocF = 19;
  tocFNIL = 20;
  tocFROMAN = 21;
  tocFSWISS = 22;
  tocFMODERN = 23;
  tocFSCRIPT = 24;
  tocFDECOR = 25;
  tocFTECH = 26;
  tocFBIDI = 27;
  tocFCHARSET = 28;
  tocFPRQ = 29;
  tocFNAME = 30;
  tocFALT = 31;
  tocFONTEMB = 32;
  tocFTNIL = 33;
  tocFTTRUETYPE = 34;
  tocFONTFILE = 35;
  tocCPG = 36;
  tocPANOSE = 37;
  tocFBIAS = 38;
  tocLISTLEVEL = 39;
  tocFILETBL = 40;
  tocFILE = 41;
  tocFID = 42;
  tocFRELATIVE = 43;
  tocFOSNUM = 44;
  tocFVALIDMAC = 45;
  tocFVALIDDOS = 46;
  tocFVALIDNTFS = 47;
  tocFVALIDHPFS = 48;
  tocFNETWORK = 49;
  tocCOLORTBL = 50;
  tocRED = 51;
  tocGREEN = 52;
  tocBLUE = 53;
  tocCB = 54;
  tocCF = 55;
  tocSTYLESHEET = 56;
  tocS = 57;
  tocCS = 58;
  tocDS = 59;
  tocKEYCODE = 60;
  tocADDITIVE = 61;
  tocSBASEDON = 62;
  tocSNEXT = 63;
  tocSAUTOUPD = 64;
  tocSHIDDEN = 65;
  tocSHIFT = 66;
  tocCTRL = 67;
  tocALT = 68;
  tocFN = 69;
  tocFS = 70;
  tocQR = 71;
  tocFI = 72;
  tocLI = 73;
  tocRI = 74;
  tocWIDOWCTRL = 75;
  tocFTNBJ = 76;
  tocFTNRESTART = 77;
  tocSECTD = 78;
  tocLINEX = 79;
  tocENDNHERE = 80;
  tocPARD = 81;
  tocPLAIN = 82;
  tocPAR = 83;
  tocLISTTABLE = 84;
  tocLISTOVERRIDETABLE = 85;
  tocLIST = 86;
  tocLISTID = 87;
  tocLISTTEMPLATEID = 88;
  tocLISTSIMPLE = 89;
  tocLISTRESTARTHDN = 90;
  tocLISTNAME = 91;
  tocLEVELSTARTAT = 92;
  tocLEVELNFC = 93;
  tocLEVELJC = 94;
  tocLEVELOLD = 95;
  tocLEVELPREV = 96;
  tocLEVELPREVSPACE = 97;
  tocLEVELINDENT = 98;
  tocLEVELSPACE = 99;
  tocLEVELTEXT = 100;
  tocLEVELNUMBERS = 101;
  tocLEVELFOLLOW = 102;
  tocLEVELLEGAL = 103;
  tocLEVELNORESTART = 104;
  tocLISTOVERRIDE = 105;
  tocLISTOVERRIDECOUNT = 106;
  tocLFOLEVEL = 107;
  tocLS = 108;
  tocLISTOVERRIDES = 109;
  tocLISTOVERRIDESTART = 110;
  tocLISTOVERRIDEFORMAT = 111;
  tocREVTBL = 112;
  tocINFO = 113;
  tocVERSION = 114;
  tocVERN = 115;
  tocEDMINS = 116;
  tocNOFPAGES = 117;
  tocNOFWORDS = 118;
  tocNOFCHARS = 119;
  tocID = 120;
  tocTITLE = 121;
  tocSUBJECT = 122;
  tocAUTHOR = 123;
  tocMANAGER = 124;
  tocCOMPANY = 125;
  tocOPERATOR = 126;
  tocCATEGORY = 127;
  tocKEYWORDS = 128;
  tocCOMMENT = 129;
  tocDOCCOMM = 130;
  tocHLINKBASE = 131;
  tocCREATIM = 132;
  tocREVTIM = 133;
  tocPRINTIM = 134;
  tocBUPTIM = 135;
  tocYR = 136;
  tocMO = 137;
  tocDY = 138;
  tocHR = 139;
  tocMIN = 140;
  tocSEC = 141;
  tocUSERPROPS = 142;
  tocPROPNAME = 143;
  tocPROPTYPE = 144;
  tocSTATICVAL = 145;
  tocLINKVAL = 146;
  tocNOFCHARSWS = 147;
  tocDEFTAB = 148;
  tocHYPHHOTZ = 149;
  tocHYPHCONSEC = 150;
  tocHYPHCAPS = 151;
  tocHYPHAUTO = 152;
  tocLINESTART = 153;
  tocFRACWIDTH = 154;
  tocNEXTFILE = 155;
  tocTEMPLATE = 156;
  tocMAKEBACKUP = 157;
  tocDEFFORMAT = 158;
  tocPSOVER = 159;
  tocDOCTEMP = 160;
  tocDEFLANG = 161;
  tocDEFLANGFE = 162;
  tocWINDOWCAPTION = 163;
  tocDOCTYPE = 164;
  tocFROMTEXT = 165;
  tocVIEWKIND = 166;
  tocVIEWSCALE = 167;
  tocVIEWZK = 168;
  tocPRIVATE = 169;
  tocFET = 170;
  tocENDNOTES = 171;
  tocENDDOC = 172;
  tocAENDNOTES = 173;
  tocAENDDOC = 174;
  tocFTNSEP = 175;
  tocFTNSEPC = 176;
  tocFTNCN = 177;
  tocAFTNSEP = 178;
  tocAFTNSEPC = 179;
  tocAFTNCN = 180;
  tocFTNTJ = 181;
  tocAFTNBJ = 182;
  tocAFTNTJ = 183;
  tocFTNSTART = 184;
  tocAFTNSTART = 185;
  tocFTNRSTPG = 186;
  tocFTNRSTCONT = 187;
  tocAFTNRESTART = 188;
  tocAFTNRSTCONT = 189;
  tocFTNNAR = 190;
  tocFTNNALC = 191;
  tocFTNNAUC = 192;
  tocFTNNRLC = 193;
  tocFTNNRUC = 194;
  tocFTNNCHI = 195;
  tocAFTNNAR = 196;
  tocAFTNNALC = 197;
  tocAFTNNAUC = 198;
  tocAFTNNRLC = 199;
  tocAFTNNRUC = 200;
  tocAFTNNCHI = 201;
  tocPAPERW = 202;
  tocPAPERH = 203;
  tocPSZ = 204;
  tocMARGL = 205;
  tocMARGR = 206;
  tocMARGT = 207;
  tocMARGB = 208;
  tocFACINGP = 209;
  tocGUTTER = 210;
  tocMARGMIRROR = 211;
  tocLANDSCAPE = 212;
  tocPGNSTART = 213;
  tocLINKSTYLES = 214;
  tocNOTABIND = 215;
  tocWRAPTRSP = 216;
  tocPRCOLBL = 217;
  tocNOEXTRASPRL = 218;
  tocNOCOLBAL = 219;
  tocCVMME = 220;
  tocSPRSTSP = 221;
  tocSPRSSPBF = 222;
  tocOTBLRUL = 223;
  tocTRANSMF = 224;
  tocBRKFRM = 225;
  tocSPRSLNSP = 226;
  tocSUBFONTBY = 227;
  tocTRUNCATEFONT = 228;
  tocTRUNCEX = 229;
  tocBDBFHDR = 230;
  tocDNTBLNSBDB = 231;
  tocEXPSHRTN = 232;
  tocLYTEXCTTP = 233;
  tocLYTPRTMET = 234;
  tocMSMCAP = 235;
  tocNOLEAD = 236;
  tocNOSPACEFORUL = 237;
  tocNOULTRLSPC = 238;
  tocNOXLATTOYEN = 239;
  tocOLDLINEWRAP = 240;
  tocSPRSBSP = 241;
  tocSPRSTSM = 242;
  tocWPJST = 243;
  tocWPSP = 244;
  tocWPTAB = 245;
  tocFORMPROT = 246;
  tocALLPROT = 247;
  tocFORMSHADE = 248;
  tocFORMDISP = 249;
  tocPRINTDATA = 250;
  tocREVPROT = 251;
  tocREVISIONS = 252;
  tocREVPROP = 253;
  tocREVBAR = 254;
  tocANNOTPROT = 255;
  tocRTLDOC = 256;
  tocLTRDOC = 257;
  tocPGBRDRHEAD = 258;
  tocPGBRDRFOOT = 259;
  tocPGBRDRT = 260;
  tocPGBRDRB = 261;
  tocPGBRDRL = 262;
  tocPGBRDRR = 263;
  tocBRDRART = 264;
  tocPGBRDROPT = 265;
  tocPGBRDRSNAP = 266;
  tocSECT = 267;
  tocSBK = 268;
  tocBINFSXN = 269;
  tocBINSXN = 270;
  tocPNSECLVL = 271;
  tocPNLVL = 272;
  tocSECTUNLOCKED = 273;
  tocSBKNONE = 274;
  tocSBKCOL = 275;
  tocSBKPAGE = 276;
  tocSBKEVEN = 277;
  tocSBKODD = 278;
  tocCOLS = 279;
  tocCOLSX = 280;
  tocCOLNO = 281;
  tocCOLSR = 282;
  tocCOLW = 283;
  tocLINEBETCOL = 284;
  tocLINEMOD = 285;
  tocLINESTARTS = 286;
  tocLINERESTART = 287;
  tocLINEPPAGE = 288;
  tocLINECONT = 289;
  tocPGWSXN = 290;
  tocPGHSXN = 291;
  tocMARGLSXN = 292;
  tocMARGRSXN = 293;
  tocMARGTSXN = 294;
  tocMARGBSXN = 295;
  tocGUTTERSXN = 296;
  tocMARGMIRSXN = 297;
  tocLNDSCPSXN = 298;
  tocTITLEPG = 299;
  tocHEADERY = 300;
  tocFOOTERY = 301;
  tocPGNSTARTS = 302;
  tocPGNCONT = 303;
  tocPGNRESTART = 304;
  tocPGNX = 305;
  tocPGNY = 306;
  tocPGNDEC = 307;
  tocPGNUCRM = 308;
  tocPGNLCRM = 309;
  tocPGNUCLTR = 310;
  tocPGNLCLTR = 311;
  tocPGNHN = 312;
  tocPGNHNSH = 313;
  tocPGNHNSP = 314;
  tocPGNHNSC = 315;
  tocPGNHNSM = 316;
  tocPGNHNSN = 317;
  tocVERTALT = 318;
  tocVERTALB = 319;
  tocVERTALC = 320;
  tocVERTALJ = 321;
  tocRTLSECT = 322;
  tocLTRSECT = 323;
  tocSTEXTFLOW = 324;
  tocHEADER = 325;
  tocFOOTER = 326;
  tocHEADERL = 327;
  tocHEADERR = 328;
  tocHEADERF = 329;
  tocFOOTERL = 330;
  tocFOOTERR = 331;
  tocFOOTERF = 332;
  tocINTBL = 333;
  tocSUBDOCUMENT = 334;
  tocROW = 335;
  tocCELL = 336;
  tocHYPHPAR = 337;
  tocKEEP = 338;
  tocNOWIDCTLPAR = 339;
  tocWIDCTLPAR = 340;
  tocKEEPN = 341;
  tocLEVEL = 342;
  tocNOLINE = 343;
  tocOUTLINELEVEL = 344;
  tocPAGEBB = 345;
  tocSBYS = 346;
  tocQL = 347;
  tocQJ = 348;
  tocQC = 349;
  tocSB = 350;
  tocSA = 351;
  tocSL = 352;
  tocSLMULT = 353;
  tocRTLPAR = 354;
  tocLTRPAR = 355;
  tocTX = 356;
  tocTB = 357;
  tocTQR = 358;
  tocTQC = 359;
  tocTQDEC = 360;
  tocTLDOT = 361;
  tocTLHYPH = 362;
  tocTLUL = 363;
  tocTLTH = 364;
  tocTLEQ = 365;
  tocPNTEXT = 366;
  tocPN = 367;
  tocPNLVLBLT = 368;
  tocPNLVLBODY = 369;
  tocPNLVLCONT = 370;
  tocPNCARD = 371;
  tocPNDEC = 372;
  tocPNUCLTR = 373;
  tocPNUCRM = 374;
  tocPNLCLTR = 375;
  tocPNLCRM = 376;
  tocPNORD = 377;
  tocPNORDT = 378;
  tocPNF = 379;
  tocPNFS = 380;
  tocPNB = 381;
  tocPNI = 382;
  tocPNCAPS = 383;
  tocPNSCAPS = 384;
  tocPNSTRIKE = 385;
  tocPNCF = 386;
  tocPNUL = 387;
  tocPNULD = 388;
  tocPNULDB = 389;
  tocPNULNONE = 390;
  tocPNULW = 391;
  tocPNNUMONCE = 392;
  tocPNACROSS = 393;
  tocPNINDENT = 394;
  tocPNSP = 395;
  tocPNPREV = 396;
  tocPNSTART = 397;
  tocPNHANG = 398;
  tocPNRESTART = 399;
  tocPNQC = 400;
  tocPNQL = 401;
  tocPNQR = 402;
  tocPNTXTB = 403;
  tocPNTXTA = 404;
  tocLISTTEXT = 405;
  tocILVL = 406;
  tocPNRAUTH = 407;
  tocPNRDATE = 408;
  tocPNRNOT = 409;
  tocPNRXST = 410;
  tocPNRRGB = 411;
  tocPNRPNBR = 412;
  tocPNRNFC = 413;
  tocPNRSTART = 414;
  tocPNRSTOP = 415;
  tocDFRAUTH = 416;
  tocDFRDATE = 417;
  tocDFRXST = 418;
  tocDFRSTART = 419;
  tocDFRSTOP = 420;
  tocBRDRT = 421;
  tocBRDRB = 422;
  tocBRDRL = 423;
  tocBRDRR = 424;
  tocBRDRBTW = 425;
  tocBRDRBAR = 426;
  tocBOX = 427;
  tocBRDRW = 428;
  tocBRSP = 429;
  tocBRDRCF = 430;
  tocBRDRS = 431;
  tocBRDRTH = 432;
  tocBRDRSH = 433;
  tocBRDRDB = 434;
  tocBRDRDOT = 435;
  tocBRDRDASH = 436;
  tocBRDRHAIR = 437;
  tocBRDRDASHSM = 438;
  tocBRDRDASHD = 439;
  tocBRDRDASHDD = 440;
  tocBRDRTRIPLE = 441;
  tocBRDRTNTHSG = 442;
  tocBRDRTHTNSG = 443;
  tocBRDRTNTHTNSG = 444;
  tocBRDRTNTHMG = 445;
  tocBRDRTHTNMG = 446;
  tocBRDRTNTHTNMG = 447;
  tocBRDRTNTHLG = 448;
  tocBRDRTHTNLG = 449;
  tocBRDRTNTHTNLG = 450;
  tocBRDRWAVY = 451;
  tocBRDRWAVYDB = 452;
  tocBRDRDASHDOTSTR = 453;
  tocBRDREMBOSS = 454;
  tocBRDRENGRAVE = 455;
  tocBRDTH = 456;
  tocSHADING = 457;
  tocCFPAT = 458;
  tocCBPAT = 459;
  tocBGHORIZ = 460;
  tocBGVERT = 461;
  tocBGFDIAG = 462;
  tocBGBDIAG = 463;
  tocBGCROSS = 464;
  tocBGDCROSS = 465;
  tocBGDKHORIZ = 466;
  tocBGDKVERT = 467;
  tocBGDKFDIAG = 468;
  tocBGDKBDIAG = 469;
  tocBGDKCROSS = 470;
  tocBGDKDCROSS = 471;
  tocABSW = 472;
  tocABSH = 473;
  tocNOWRAP = 474;
  tocDXFRTEXT = 475;
  tocDFRMTXTX = 476;
  tocDFRMTXTY = 477;
  tocDROPCAPLI = 478;
  tocDROPCAPT = 479;
  tocPHMRG = 480;
  tocPHPG = 481;
  tocPHCOL = 482;
  tocPOSX = 483;
  tocPOSNEGX = 484;
  tocPOSXC = 485;
  tocPOSXI = 486;
  tocPOSXO = 487;
  tocPOSXL = 488;
  tocPOSXR = 489;
  tocPVMRG = 490;
  tocPVPG = 491;
  tocPVPARA = 492;
  tocPOSY = 493;
  tocPOSNEGY = 494;
  tocPOSYT = 495;
  tocPOSYIL = 496;
  tocPOSYB = 497;
  tocPOSYC = 498;
  tocABSLOCK = 499;
  tocOVERLAY = 500;
  tocPOSYIN = 501;
  tocPOSYOUT = 502;
  tocDXFRTEST = 503;
  tocTROWD = 504;
  tocTRGAPH = 505;
  tocTRLEFT = 506;
  tocTRRH = 507;
  tocTRHDR = 508;
  tocTRKEEP = 509;
  tocTRQL = 510;
  tocTRQR = 511;
  tocTRQC = 512;
  tocLTRROW = 513;
  tocRTLROW = 514;
  tocTRBRDRT = 515;
  tocTRBRDRL = 516;
  tocTRBRDRB = 517;
  tocTRBRDRR = 518;
  tocTRBRDRH = 519;
  tocTRBRDRV = 520;
  tocCLMGF = 521;
  tocCLMRG = 522;
  tocCELLX = 523;
  tocCLBRDRT = 524;
  tocCLBRDRL = 525;
  tocCLBRDRB = 526;
  tocCLBRDRR = 527;
  tocCLCFPAT = 528;
  tocCLCBPAT = 529;
  tocCLSHDNG = 530;
  tocCLBGHORIZ = 531;
  tocCLBGVERT = 532;
  tocCLBGFDIAG = 533;
  tocCLBGBDIAG = 534;
  tocCLBGCROSS = 535;
  tocCLBGDCROSS = 536;
  tocCLBGDKHOR = 537;
  tocCLBGDKVERT = 538;
  tocCLBGDKFDIAG = 539;
  tocCLBGDKBDIAG = 540;
  tocCLBGDKCROSS = 541;
  tocCLBGDKDCROSS = 542;
  tocCELLXS = 543;
  tocCELLS = 544;
  tocTCELLD = 545;
  tocCLVERTALT = 546;
  tocCLVERTALC = 547;
  tocCLVERTALB = 548;
  tocCLTXLRTB = 549;
  tocCLTXTBRL = 550;
  tocCLBRDR = 551;
  tocB = 552;
  tocANIMTEXT = 553;
  tocCAPS = 554;
  tocCHARSCALEX = 555;
  tocDELETED = 556;
  tocDN = 557;
  tocEMBO = 558;
  tocIMPR = 559;
  tocSUB = 560;
  tocNOSUPERSUB = 561;
  tocEXPND = 562;
  tocEXPNDTW = 563;
  tocKERNING = 564;
  tocI = 565;
  tocOUTL = 566;
  tocSCAPS = 567;
  tocSHAD = 568;
  tocSTRIKE = 569;
  tocSTRIKEDL = 570;
  tocUL = 571;
  tocULD = 572;
  tocULDASH = 573;
  tocULDASHD = 574;
  tocULDASHDD = 575;
  tocULDB = 576;
  tocULNONE = 577;
  tocULTH = 578;
  tocULW = 579;
  tocULWAVE = 580;
  tocUP = 581;
  tocSUPER = 582;
  tocV = 583;
  tocRTLCH = 584;
  tocLTRCH = 585;
  tocCCHS = 586;
  tocLANG = 587;
  tocCHSHDNG = 588;
  tocCHCFPAT = 589;
  tocCHCBPAT = 590;
  tocCHBGHORIZ = 591;
  tocCHBGVERT = 592;
  tocCHBGFDIAG = 593;
  tocCHBGBDIAG = 594;
  tocCHBGCROSS = 595;
  tocCHBGDCROSS = 596;
  tocCHBGDKHORIZ = 597;
  tocCHBGDKVERT = 598;
  tocCHBGDKFDIAG = 599;
  tocCHBGDKBDIAG = 600;
  tocCHBGDKCROSS = 601;
  tocCHBGDKDCROSS = 602;
  tocCHBRDR = 603;
  tocREVISED = 604;
  tocREVAUTH = 605;
  tocREVDTTM = 606;
  tocCRAUTH = 607;
  tocCRDATE = 608;
  tocREVAUTHDEL = 609;
  tocREVDTTMDEL = 610;
  tocAF = 611;
  tocAB = 612;
  tocAU = 613;
  tocAI = 614;
  tocACAPS = 615;
  tocACF = 616;
  tocADN = 617;
  tocAEXPND = 618;
  tocAFS = 619;
  tocALANG = 620;
  tocAOUTL = 621;
  tocASCAPS = 622;
  tocASHAD = 623;
  tocASTRIKE = 624;
  tocAUL = 625;
  tocAULD = 626;
  tocAULDB = 627;
  tocAULNONE = 628;
  tocAULW = 629;
  tocAUP = 630;
  tocHIGHLIGHT = 631;
  tocCHDATE = 632;
  tocCHDPL = 633;
  tocCHDPA = 634;
  tocCHTIME = 635;
  tocCHPGN = 636;
  tocSECTNUM = 637;
  tocCHFTN = 638;
  tocCHATN = 639;
  tocCHFTNSEP = 640;
  tocCHFTNSEPC = 641;
  tocPAGE = 642;
  tocCOLUMN = 643;
  tocLINE = 644;
  tocSOFTPAGE = 645;
  tocSOFTCOL = 646;
  tocSOFTLINE = 647;
  tocSOFTLHEIGHT = 648;
  tocTAB = 649;
  tocEMDASH = 650;
  tocENDASH = 651;
  tocEMSPACE = 652;
  tocENSPACE = 653;
  tocBULLET = 654;
  tocLQUOTE = 655;
  tocRQUOTE = 656;
  tocLDBLQUOTE = 657;
  tocRDBLQUOTE = 658;
  tocLTRMARK = 659;
  tocRTLMARK = 660;
  tocZWJ = 661;
  tocZWNJ = 662;
  tocDOCVAR = 663;
  tocBKMKEND = 664;
  tocBKMKCOLF = 665;
  tocBKMKCOLL = 666;
  tocPICT = 667;
  tocSHPPICT = 668;
  tocEMFBLIP = 669;
  tocPNGBLIP = 670;
  tocJPEGBLIP = 671;
  tocMACPICT = 672;
  tocPMMETAFILE = 673;
  tocWMETAFILE = 674;
  tocDIBITMAP = 675;
  tocWBITMAP = 676;
  tocWBMBITSPIXEL = 677;
  tocWBMPLANES = 678;
  tocWBMWIDTHBYTES = 679;
  tocPICW = 680;
  tocPICH = 681;
  tocPICWGOAL = 682;
  tocPICHGOAL = 683;
  tocPICSCALEX = 684;
  tocPICSCALEY = 685;
  tocPICSCALED = 686;
  tocPICCROPT = 687;
  tocPICCROPB = 688;
  tocPICCROPR = 689;
  tocPICCROPL = 690;
  tocPICBMP = 691;
  tocPICBPP = 692;
  tocBIN = 693;
  tocNONSHPPICT = 694;
  tocPICPROP = 695;
  tocBLIPUPI = 696;
  tocBLIPUID = 697;
  tocBLIPTAG = 698;
  tocOBJECT = 699;
  tocOBJEMB = 700;
  tocOBJLINK = 701;
  tocOBJAUTLINK = 702;
  tocOBJSUB = 703;
  tocOBJPUB = 704;
  tocOBJICEMB = 705;
  tocLINKSELF = 706;
  tocOBJLOCK = 707;
  tocOBJUPDATE = 708;
  tocOBJCLASS = 709;
  tocOBJNAME = 710;
  tocOBJTIME = 711;
  tocRSLTMERGE = 712;
  tocRSLTRTF = 713;
  tocRSLTTXT = 714;
  tocRSLTPICT = 715;
  tocRSLTBMP = 716;
  tocOBJSETSIZE = 717;
  tocOBJALIGN = 718;
  tocOBJTRANSY = 719;
  tocOBJCROPT = 720;
  tocOBJCROPB = 721;
  tocOBJCROPL = 722;
  tocOBJCROPR = 723;
  tocOBJSCALEX = 724;
  tocOBJSCALEY = 725;
  tocOBJH = 726;
  tocOBJW = 727;
  tocOBJDATA = 728;
  tocOBJALIAS = 729;
  tocOBJSECT = 730;
  tocRESULT = 731;
  tocOBJHTML = 732;
  tocOBJOCX = 733;
  tocOBJATTPH = 734;
  tocBKMKPUB = 735;
  tocPUBAUTO = 736;
  tocDO = 737;
  tocDOBXPAGE = 738;
  tocDOBXCOLUMN = 739;
  tocDOBXMARGIN = 740;
  tocDOBYPAGE = 741;
  tocDOBYPARA = 742;
  tocDOBYMARGIN = 743;
  tocDODHGT = 744;
  tocDOLOCK = 745;
  tocDPGROUP = 746;
  tocDPCOUNT = 747;
  tocDPENDGROUP = 748;
  tocDPCALLOUT = 749;
  tocDPCOOFFSET = 750;
  tocDPCOLENGTH = 751;
  tocDPLINE = 752;
  tocDPRECT = 753;
  tocDPROUNDR = 754;
  tocDPTXBX = 755;
  tocDPTXBXMAR = 756;
  tocDPTXBXTEXT = 757;
  tocDPELLIPSE = 758;
  tocDPARC = 759;
  tocDPARCFLIPX = 760;
  tocDPARCFLIPY = 761;
  tocDPPOLYLINE = 762;
  tocDPPOLYGON = 763;
  tocDPPOLYCOUNT = 764;
  tocDPPTX = 765;
  tocDPPTY = 766;
  tocDPX = 767;
  tocDPY = 768;
  tocDPXSIZE = 769;
  tocDPYSIZE = 770;
  tocDPCOTRIGHT = 771;
  tocDPCOTSINGLE = 772;
  tocDPCOTDOUBLE = 773;
  tocDPCOTTRIPLE = 774;
  tocDPCOA = 775;
  tocDPCOACCENT = 776;
  tocDPCOSMARTA = 777;
  tocDPCOBESTFIT = 778;
  tocDPCOMINUSX = 779;
  tocDPCOMINUSY = 780;
  tocDPCOBORDER = 781;
  tocDPCODTOP = 782;
  tocDPCODCENTER = 783;
  tocDPCODBOTTOM = 784;
  tocDPCODABS = 785;
  tocDPLINEW = 786;
  tocDPLINESOLID = 787;
  tocDPLINEHOLLOW = 788;
  tocDPLINEDASH = 789;
  tocDPLINEDOT = 790;
  tocDPLINEDADO = 791;
  tocDPLINEDADODO = 792;
  tocDPLINEGRAY = 793;
  tocDPLINECOR = 794;
  tocDPLINECOG = 795;
  tocDPLINECOB = 796;
  tocDPLINEPAL = 797;
  tocDPFILLPAT = 798;
  tocDPFILLFGGRAY = 799;
  tocDPFILLFGCR = 800;
  tocDPFILLFGCG = 801;
  tocDPFILLFGCB = 802;
  tocDPFILLFGPAL = 803;
  tocDPFILLBGGRAY = 804;
  tocDPFILLBGCR = 805;
  tocDPFILLBGCG = 806;
  tocDPFILLBGCB = 807;
  tocDPFILLBGPAL = 808;
  tocDPASTARTL = 809;
  tocDPASTARTW = 810;
  tocDPASTARTSOL = 811;
  tocDPASTARTHOL = 812;
  tocDPAENDL = 813;
  tocDPAENDW = 814;
  tocDPAENDSOL = 815;
  tocDPAENDHOL = 816;
  tocDPSHADOW = 817;
  tocDPSHADX = 818;
  tocDPSHADY = 819;
  tocDPCODESCENT = 820;
  tocSHP = 821;
  tocSHPINST = 822;
  tocSPP = 823;
  tocSN = 824;
  tocSP = 825;
  tocSHPRSLT = 826;
  tocSHPLEFT = 827;
  tocSHPTOP = 828;
  tocSHPBOTTOM = 829;
  tocSHPRIGHT = 830;
  tocSHPLID = 831;
  tocSHPZ = 832;
  tocSHPFHDR = 833;
  tocSHPBXPAGE = 834;
  tocSHPBXMARGIN = 835;
  tocSHPBXCOLUMN = 836;
  tocSHPBYPAGE = 837;
  tocSHPBYMARGIN = 838;
  tocSHPBYPARA = 839;
  tocSHPWR = 840;
  tocSHPWRK = 841;
  tocSHPFBLWTXT = 842;
  tocSHPLOCKANCHOR = 843;
  tocSHPTXT = 844;
  tocSHPGRP = 845;
  tocBACKGROUND = 846;
  tocSV = 847;
  tocHL = 848;
  tocHLLOC = 849;
  tocHLSRC = 850;
  tocHLFR = 851;
  tocFOOTNOTE = 852;
  tocPU = 853;
  tocFTNALT = 854;
  tocATNID = 855;
  tocANNOTATION = 856;
  tocATRFSTART = 857;
  tocATRFEND = 858;
  tocATNAUTHOR = 859;
  tocATNREF = 860;
  tocATNTIME = 861;
  tocATNICN = 862;
  tocFIELD = 863;
  tocFLDINST = 864;
  tocFLDRSLT = 865;
  tocFLDDIRTY = 866;
  tocFLDEDIT = 867;
  tocFLDLOCK = 868;
  tocFLDPRIV = 869;
  tocFLDALT = 870;
  tocDATAFIELD = 871;
  tocFLDTYPE = 872;
  tocDATE = 873;
  tocTIME = 874;
  tocWPEQN = 875;
  tocFORMFIELD = 876;
  tocFFTYPE = 877;
  tocFFOWNHELP = 878;
  tocFFHELPTEXT = 879;
  tocFFOWNSTAT = 880;
  tocFFSTATTEXT = 881;
  tocFFPROT = 882;
  tocFFSIZE = 883;
  tocFFTYPETXT = 884;
  tocFFRECALC = 885;
  tocFFHASLISTBOX = 886;
  tocFFMAXLEN = 887;
  tocFFHPS = 888;
  tocFFNAME = 889;
  tocFFDEFTEXT = 890;
  tocFFDEFRES = 891;
  tocFFFORMAT = 892;
  tocFFENTRYMCR = 893;
  tocFFEXITMCR = 894;
  tocFFL = 895;
  tocFFRES = 896;
  tocXE = 897;
  tocXEF = 898;
  tocBXE = 899;
  tocIXE = 900;
  tocTXE = 901;
  tocRXE = 902;
  tocTC = 903;
  tocTCN = 904;
  tocTCF = 905;
  tocTCL = 906;

function RTFLookup(const aName : string) : LongInt;

implementation
uses
  Sysutils, LMDDataType;

type
  { ************************************************************************** }
  TLMDTerminalAssociation = class (TLMDAssociation)
  private
    FCode : LongInt;
  public
    property Code : LongInt read FCode write FCode;
  end;

  { ************************************************************************** }
  TLMDTerminalHashTable = class (TLMDHashTable)
  private
    function GetItem(const index : string) : TLMDTerminalAssociation;
  public
    constructor Create(aMaxSize : integer); overload;
    //constructor Create(aMaxSize : integer; aItemClass: TLMDAssociationClass); overload;
    function Add(const aKey : string; aCode : LongInt) : TLMDTerminalAssociation;
    property Items[const index : string] : TLMDTerminalAssociation read GetItem; default;
  end;

var
  RTFLookupTable : TLMDTerminalHashTable;

procedure MakeRTFLookupTable; forward;
  function RTFLookup(const aName : string) : LongInt;
var
  Term : TLMDTerminalAssociation;
begin
  MakeRTFLookupTable;
  Term := RTFLookupTable[aName];
  if assigned(Term) then
    result := Term.Code
  else
    Result := -1;
{
  result := -1;
  if not assigned(RTFLookupTable) then Exit;
  Term := RTFLookupTable[aName];
  if not assigned(Term) then Exit;
  result := Term.Code;
}
end;

{ ********************************* TLMDTerminalHashTable *********************** }
{---------------------------------- private -----------------------------------}
function TLMDTerminalHashTable.GetItem(const index : string) : TLMDTerminalAssociation;
begin result := TLMDTerminalAssociation(inherited GetItem(index)); end;
{---------------------------------- protected ---------------------------------}
{---------------------------------- public ------------------------------------}
constructor TLMDTerminalHashTable.Create(aMaxSize : integer);
begin inherited Create(aMaxSize, TLMDTerminalAssociation); end;

{------------------------------------------------------------------------------}
{constructor TLMDTerminalHashTable.Create(aMaxSize : integer; aItemClass: TLMDAssociationClass);
begin inherited; end;}

{------------------------------------------------------------------------------}
function TLMDTerminalHashTable.Add(const aKey : string; aCode : LongInt) : TLMDTerminalAssociation;
begin
  result := TLMDTerminalAssociation(inherited Add(aKey));
  if assigned (result) then
    result.Code := aCode;
end;

procedure MakeRTFLookupTable;
begin
  if not Assigned(RTFLookupTable) then
    begin
      RTFLookupTable := TLMDTerminalHashTable.Create(1000);
      with RTFLookupTable do
        begin
          Add('rtf', tocRTF);
          Add('ansi', tocANSI);
          Add('mac', tocMAC);
          Add('pc', tocPC);
          Add('pca', tocPCA);
          Add('ansicpg', tocANSICPG);
          Add('uc', tocUC);
          Add('deff', tocDEFF);
          Add('fonttbl', tocFONTTBL);
          Add('f', tocF);
          Add('fnil', tocFNIL);
          Add('froman', tocFROMAN);
          Add('fswiss', tocFSWISS);
          Add('fmodern', tocFMODERN);
          Add('fscript', tocFSCRIPT);
          Add('fdecor', tocFDECOR);
          Add('ftech', tocFTECH);
          Add('fbidi', tocFBIDI);
          Add('fcharset', tocFCHARSET);
          Add('fprq', tocFPRQ);
          Add('fname', tocFNAME);
          Add('cpg', tocCPG);
          Add('panose', tocPANOSE);
          Add('falt', tocFALT);
          Add('fontemb', tocFONTEMB);
          Add('ftnil', tocFTNIL);
          Add('fttruetype', tocFTTRUETYPE);
          Add('fontfile', tocFONTFILE);

          Add('filetbl', tocFILETBL);
          Add('file', tocFILE);
          Add('fid', tocFID);
          Add('frelative', tocFRELATIVE);
          Add('fosnum', tocFOSNUM);
          Add('fvalidmac', tocFVALIDMAC);
          Add('fvaliddos', tocFVALIDDOS);
          Add('fvalidntfs', tocFVALIDNTFS);
          Add('fvalidhpfs', tocFVALIDHPFS);
          Add('fnetwork', tocFNETWORK);
          Add('colortbl', tocCOLORTBL);
          Add('red', tocRED);
          Add('green', tocGREEN);
          Add('blue', tocBLUE);
          Add('stylesheet', tocSTYLESHEET);
          Add('s', tocS);
          Add('cs', tocCS);
          Add('ds', tocDS);
          Add('keycode', tocKEYCODE);
          Add('shift', tocSHIFT);
          Add('ctrl', tocCTRL);
          Add('alt', tocALT);
          Add('fn', tocFN);
          Add('additive', tocADDITIVE);
          Add('sbasedon', tocSBASEDON);
          Add('snext', tocSNEXT);
          Add('brdrt', tocBRDRT);
          Add('brdrb', tocBRDRB);
          Add('brdrl', tocBRDRL);
          Add('brdrr', tocBRDRR);
          Add('brdrbtw', tocBRDRBTW);
          Add('brdrbar', tocBRDRBAR);
          Add('box', tocBOX);
          Add('brdrs', tocBRDRS);
          Add('brdrth', tocBRDRTH);
          Add('brdrsh', tocBRDRSH);
          Add('brdrdb', tocBRDRDB);
          Add('brdrdot', tocBRDRDOT);
          Add('brdrdash', tocBRDRDASH);
          Add('brdrhair', tocBRDRHAIR);
          Add('brdrdashsm', tocBRDRDASHSM);
          Add('brdrdashd', tocBRDRDASHD);
          Add('brdrdashdd', tocBRDRDASHDD);
          Add('brdrtriple', tocBRDRTRIPLE);
          Add('brdrtnthsg', tocBRDRTNTHSG);
          Add('brdrthtnsg', tocBRDRTHTNSG);
          Add('brdrtnthtnsg', tocBRDRTNTHTNSG);
          Add('brdrtnthmg', tocBRDRTNTHMG);
          Add('brdrthtnmg', tocBRDRTHTNMG);
          Add('brdrtnthtnmg', tocBRDRTNTHTNMG);
          Add('brdrtnthlg', tocBRDRTNTHLG);
          Add('brdrthtnlg', tocBRDRTHTNLG);
          Add('brdrtnthtnlg', tocBRDRTNTHTNLG);
          Add('brdrwavy', tocBRDRWAVY);
          Add('brdrwavydb', tocBRDRWAVYDB);
          Add('brdrdashdotstr', tocBRDRDASHDOTSTR);
          Add('brdremboss', tocBRDREMBOSS);
          Add('brdrengrave', tocBRDRENGRAVE);
          Add('brdrw', tocBRDRW);
          Add('brsp', tocBRSP);
          Add('brdrcf', tocBRDRCF);
          Add('upr', tocUPR);
          Add('ud', tocUD);
          Add('u', tocU);
          Add('ucl', tocUCL);
          Add('bkmkstart', tocBKMKSTART);
          Add('fbias', tocFBIAS);
          Add('listlevel', tocLISTLEVEL);
          Add('cb', tocCB);
          Add('cf', tocCF);
          Add('sautoupd', tocSAUTOUPD);
          Add('shidden', tocSHIDDEN);
          Add('fs', tocFS);
          Add('qr', tocQR);
          Add('fi', tocFI);
          Add('li', tocLI);
          Add('ri', tocRI);
          Add('widowctrl', tocWIDOWCTRL);
          Add('ftnbj', tocFTNBJ);
          Add('ftnrestart', tocFTNRESTART);
          Add('sectd', tocSECTD);
          Add('linex', tocLINEX);
          Add('endnhere', tocENDNHERE);
          Add('pard', tocPARD);
          Add('plain', tocPLAIN);
          Add('par', tocPAR);
          Add('listtable', tocLISTTABLE);
          Add('listoverridetable', tocLISTOVERRIDETABLE);
          Add('list', tocLIST);
          Add('listid', tocLISTID);
          Add('listtemplateid', tocLISTTEMPLATEID);
          Add('listsimple', tocLISTSIMPLE);
          Add('listrestarthdn', tocLISTRESTARTHDN);
          Add('listname', tocLISTNAME);
          Add('levelstartat', tocLEVELSTARTAT);
          Add('levelnfc', tocLEVELNFC);
          Add('leveljc', tocLEVELJC);
          Add('levelold', tocLEVELOLD);
          Add('levelprev', tocLEVELPREV);
          Add('levelprevspace', tocLEVELPREVSPACE);
          Add('levelindent', tocLEVELINDENT);
          Add('levelspace', tocLEVELSPACE);
          Add('leveltext', tocLEVELTEXT);
          Add('levelnumbers', tocLEVELNUMBERS);
          Add('levelfollow', tocLEVELFOLLOW);
          Add('levellegal', tocLEVELLEGAL);
          Add('levelnorestart', tocLEVELNORESTART);
          Add('listoverride', tocLISTOVERRIDE);
          Add('listoverridecount', tocLISTOVERRIDECOUNT);
          Add('lfolevel', tocLFOLEVEL);
          Add('ls', tocLS);
          Add('listoverrides', tocLISTOVERRIDES);
          Add('listoverridestart', tocLISTOVERRIDESTART);
          Add('listoverrideformat', tocLISTOVERRIDEFORMAT);
          Add('revtbl', tocREVTBL);
          Add('info', tocINFO);
          Add('version', tocVERSION);
          Add('vern', tocVERN);
          Add('edmins', tocEDMINS);
          Add('nofpages', tocNOFPAGES);
          Add('nofwords', tocNOFWORDS);
          Add('nofchars', tocNOFCHARS);
          Add('id', tocID);
          Add('title', tocTITLE);
          Add('subject', tocSUBJECT);
          Add('author', tocAUTHOR);
          Add('manager', tocMANAGER);
          Add('company', tocCOMPANY);
          Add('operator', tocOPERATOR);
          Add('category', tocCATEGORY);
          Add('keywords', tocKEYWORDS);
          Add('comment', tocCOMMENT);
          Add('doccomm', tocDOCCOMM);
          Add('hlinkbase', tocHLINKBASE);
          Add('creatim', tocCREATIM);
          Add('revtim', tocREVTIM);
          Add('printim', tocPRINTIM);
          Add('buptim', tocBUPTIM);
          Add('yr', tocYR);
          Add('mo', tocMO);
          Add('dy', tocDY);
          Add('hr', tocHR);
          Add('min', tocMIN);
          Add('sec', tocSEC);
          Add('userprops', tocUSERPROPS);
          Add('propname', tocPROPNAME);
          Add('proptype', tocPROPTYPE);
          Add('staticval', tocSTATICVAL);
          Add('linkval', tocLINKVAL);
          Add('nofcharsws', tocNOFCHARSWS);
          Add('deftab', tocDEFTAB);
          Add('hyphhotz', tocHYPHHOTZ);
          Add('hyphconsec', tocHYPHCONSEC);
          Add('hyphcaps', tocHYPHCAPS);
          Add('hyphauto', tocHYPHAUTO);
          Add('linestart', tocLINESTART);
          Add('fracwidth', tocFRACWIDTH);
          Add('nextfile', tocNEXTFILE);
          Add('template', tocTEMPLATE);
          Add('makebackup', tocMAKEBACKUP);
          Add('defformat', tocDEFFORMAT);
          Add('psover', tocPSOVER);
          Add('doctemp', tocDOCTEMP);
          Add('deflang', tocDEFLANG);
          Add('deflangfe', tocDEFLANGFE);
          Add('windowcaption', tocWINDOWCAPTION);
          Add('doctype', tocDOCTYPE);
          Add('fromtext', tocFROMTEXT);
          Add('viewkind', tocVIEWKIND);
          Add('viewscale', tocVIEWSCALE);
          Add('viewzk', tocVIEWZK);
          Add('private', tocPRIVATE);
          Add('fet', tocFET);
          Add('endnotes', tocENDNOTES);
          Add('enddoc', tocENDDOC);
          Add('aendnotes', tocAENDNOTES);
          Add('aenddoc', tocAENDDOC);
          Add('ftnsep', tocFTNSEP);
          Add('ftnsepc', tocFTNSEPC);
          Add('ftncn', tocFTNCN);
          Add('aftnsep', tocAFTNSEP);
          Add('aftnsepc', tocAFTNSEPC);
          Add('aftncn', tocAFTNCN);
          Add('ftntj', tocFTNTJ);
          Add('aftnbj', tocAFTNBJ);
          Add('aftntj', tocAFTNTJ);
          Add('ftnstart', tocFTNSTART);
          Add('aftnstart', tocAFTNSTART);
          Add('ftnrstpg', tocFTNRSTPG);
          Add('ftnrstcont', tocFTNRSTCONT);
          Add('aftnrestart', tocAFTNRESTART);
          Add('aftnrstcont', tocAFTNRSTCONT);
          Add('ftnnar', tocFTNNAR);
          Add('ftnnalc', tocFTNNALC);
          Add('ftnnauc', tocFTNNAUC);
          Add('ftnnrlc', tocFTNNRLC);
          Add('ftnnruc', tocFTNNRUC);
          Add('ftnnchi', tocFTNNCHI);
          Add('aftnnar', tocAFTNNAR);
          Add('aftnnalc', tocAFTNNALC);
          Add('aftnnauc', tocAFTNNAUC);
          Add('aftnnrlc', tocAFTNNRLC);
          Add('aftnnruc', tocAFTNNRUC);
          Add('aftnnchi', tocAFTNNCHI);
          Add('paperw', tocPAPERW);
          Add('paperh', tocPAPERH);
          Add('psz', tocPSZ);
          Add('margl', tocMARGL);
          Add('margr', tocMARGR);
          Add('margt', tocMARGT);
          Add('margb', tocMARGB);
          Add('facingp', tocFACINGP);
          Add('gutter', tocGUTTER);
          Add('margmirror', tocMARGMIRROR);
          Add('landscape', tocLANDSCAPE);
          Add('pgnstart', tocPGNSTART);
          Add('linkstyles', tocLINKSTYLES);
          Add('notabind', tocNOTABIND);
          Add('wraptrsp', tocWRAPTRSP);
          Add('prcolbl', tocPRCOLBL);
          Add('noextrasprl', tocNOEXTRASPRL);
          Add('nocolbal', tocNOCOLBAL);
          Add('cvmme', tocCVMME);
          Add('sprstsp', tocSPRSTSP);
          Add('sprsspbf', tocSPRSSPBF);
          Add('otblrul', tocOTBLRUL);
          Add('transmf', tocTRANSMF);
          Add('brkfrm', tocBRKFRM);
          Add('sprslnsp', tocSPRSLNSP);
          Add('subfontby', tocSUBFONTBY);
          Add('truncatefont', tocTRUNCATEFONT);
          Add('truncex', tocTRUNCEX);
          Add('bdbfhdr', tocBDBFHDR);
          Add('dntblnsbdb', tocDNTBLNSBDB);
          Add('expshrtn', tocEXPSHRTN);
          Add('lytexcttp', tocLYTEXCTTP);
          Add('lytprtmet', tocLYTPRTMET);
          Add('msmcap', tocMSMCAP);
          Add('nolead', tocNOLEAD);
          Add('nospaceforul', tocNOSPACEFORUL);
          Add('noultrlspc', tocNOULTRLSPC);
          Add('noxlattoyen', tocNOXLATTOYEN);
          Add('oldlinewrap', tocOLDLINEWRAP);
          Add('sprsbsp', tocSPRSBSP);
          Add('sprstsm', tocSPRSTSM);
          Add('wpjst', tocWPJST);
          Add('wpsp', tocWPSP);
          Add('wptab', tocWPTAB);
          Add('formprot', tocFORMPROT);
          Add('allprot', tocALLPROT);
          Add('formshade', tocFORMSHADE);
          Add('formdisp', tocFORMDISP);
          Add('printdata', tocPRINTDATA);
          Add('revprot', tocREVPROT);
          Add('revisions', tocREVISIONS);
          Add('revprop', tocREVPROP);
          Add('revbar', tocREVBAR);
          Add('annotprot', tocANNOTPROT);
          Add('rtldoc', tocRTLDOC);
          Add('ltrdoc', tocLTRDOC);
          Add('pgbrdrhead', tocPGBRDRHEAD);
          Add('pgbrdrfoot', tocPGBRDRFOOT);
          Add('pgbrdrt', tocPGBRDRT);
          Add('pgbrdrb', tocPGBRDRB);
          Add('pgbrdrl', tocPGBRDRL);
          Add('pgbrdrr', tocPGBRDRR);
          Add('brdrart', tocBRDRART);
          Add('pgbrdropt', tocPGBRDROPT);
          Add('pgbrdrsnap', tocPGBRDRSNAP);
          Add('sect', tocSECT);
          Add('sbk', tocSBK);
          Add('binfsxn', tocBINFSXN);
          Add('binsxn', tocBINSXN);
          Add('pnseclvl', tocPNSECLVL);
          Add('pnlvl', tocPNLVL);
          Add('sectunlocked', tocSECTUNLOCKED);
          Add('sbknone', tocSBKNONE);
          Add('sbkcol', tocSBKCOL);
          Add('sbkpage', tocSBKPAGE);
          Add('sbkeven', tocSBKEVEN);
          Add('sbkodd', tocSBKODD);
          Add('cols', tocCOLS);
          Add('colsx', tocCOLSX);
          Add('colno', tocCOLNO);
          Add('colsr', tocCOLSR);
          Add('colw', tocCOLW);
          Add('linebetcol', tocLINEBETCOL);
          Add('linemod', tocLINEMOD);
          Add('linestarts', tocLINESTARTS);
          Add('linerestart', tocLINERESTART);
          Add('lineppage', tocLINEPPAGE);
          Add('linecont', tocLINECONT);
          Add('pgwsxn', tocPGWSXN);
          Add('pghsxn', tocPGHSXN);
          Add('marglsxn', tocMARGLSXN);
          Add('margrsxn', tocMARGRSXN);
          Add('margtsxn', tocMARGTSXN);
          Add('margbsxn', tocMARGBSXN);
          Add('guttersxn', tocGUTTERSXN);
          Add('margmirsxn', tocMARGMIRSXN);
          Add('lndscpsxn', tocLNDSCPSXN);
          Add('titlepg', tocTITLEPG);
          Add('headery', tocHEADERY);
          Add('footery', tocFOOTERY);
          Add('pgnstarts', tocPGNSTARTS);
          Add('pgncont', tocPGNCONT);
          Add('pgnrestart', tocPGNRESTART);
          Add('pgnx', tocPGNX);
          Add('pgny', tocPGNY);
          Add('pgndec', tocPGNDEC);
          Add('pgnucrm', tocPGNUCRM);
          Add('pgnlcrm', tocPGNLCRM);
          Add('pgnucltr', tocPGNUCLTR);
          Add('pgnlcltr', tocPGNLCLTR);
          Add('pgnhn', tocPGNHN);
          Add('pgnhnsh', tocPGNHNSH);
          Add('pgnhnsp', tocPGNHNSP);
          Add('pgnhnsc', tocPGNHNSC);
          Add('pgnhnsm', tocPGNHNSM);
          Add('pgnhnsn', tocPGNHNSN);
          Add('vertalt', tocVERTALT);
          Add('vertalb', tocVERTALB);
          Add('vertalc', tocVERTALC);
          Add('vertalj', tocVERTALJ);
          Add('rtlsect', tocRTLSECT);
          Add('ltrsect', tocLTRSECT);
          Add('stextflow', tocSTEXTFLOW);
          Add('header', tocHEADER);
          Add('footer', tocFOOTER);
          Add('headerl', tocHEADERL);
          Add('headerr', tocHEADERR);
          Add('headerf', tocHEADERF);
          Add('footerl', tocFOOTERL);
          Add('footerr', tocFOOTERR);
          Add('footerf', tocFOOTERF);
          Add('intbl', tocINTBL);
          Add('subdocument', tocSUBDOCUMENT);
          Add('row', tocROW);
          Add('cell', tocCELL);
          Add('hyphpar', tocHYPHPAR);
          Add('keep', tocKEEP);
          Add('nowidctlpar', tocNOWIDCTLPAR);
          Add('widctlpar', tocWIDCTLPAR);
          Add('keepn', tocKEEPN);
          Add('level', tocLEVEL);
          Add('noline', tocNOLINE);
          Add('outlinelevel', tocOUTLINELEVEL);
          Add('pagebb', tocPAGEBB);
          Add('sbys', tocSBYS);
          Add('ql', tocQL);
          Add('qj', tocQJ);
          Add('qc', tocQC);
          Add('sb', tocSB);
          Add('sa', tocSA);
          Add('sl', tocSL);
          Add('slmult', tocSLMULT);
          Add('rtlpar', tocRTLPAR);
          Add('ltrpar', tocLTRPAR);
          Add('tx', tocTX);
          Add('tb', tocTB);
          Add('tqr', tocTQR);
          Add('tqc', tocTQC);
          Add('tqdec', tocTQDEC);
          Add('tldot', tocTLDOT);
          Add('tlhyph', tocTLHYPH);
          Add('tlul', tocTLUL);
          Add('tlth', tocTLTH);
          Add('tleq', tocTLEQ);
          Add('pntext', tocPNTEXT);
          Add('pn', tocPN);
          Add('pnlvlblt', tocPNLVLBLT);
          Add('pnlvlbody', tocPNLVLBODY);
          Add('pnlvlcont', tocPNLVLCONT);
          Add('pncard', tocPNCARD);
          Add('pndec', tocPNDEC);
          Add('pnucltr', tocPNUCLTR);
          Add('pnucrm', tocPNUCRM);
          Add('pnlcltr', tocPNLCLTR);
          Add('pnlcrm', tocPNLCRM);
          Add('pnord', tocPNORD);
          Add('pnordt', tocPNORDT);
          Add('pnf', tocPNF);
          Add('pnfs', tocPNFS);
          Add('pnb', tocPNB);
          Add('pni', tocPNI);
          Add('pncaps', tocPNCAPS);
          Add('pnscaps', tocPNSCAPS);
          Add('pnstrike', tocPNSTRIKE);
          Add('pncf', tocPNCF);
          Add('pnul', tocPNUL);
          Add('pnuld', tocPNULD);
          Add('pnuldb', tocPNULDB);
          Add('pnulnone', tocPNULNONE);
          Add('pnulw', tocPNULW);
          Add('pnnumonce', tocPNNUMONCE);
          Add('pnacross', tocPNACROSS);
          Add('pnindent', tocPNINDENT);
          Add('pnsp', tocPNSP);
          Add('pnprev', tocPNPREV);
          Add('pnstart', tocPNSTART);
          Add('pnhang', tocPNHANG);
          Add('pnrestart', tocPNRESTART);
          Add('pnqc', tocPNQC);
          Add('pnql', tocPNQL);
          Add('pnqr', tocPNQR);
          Add('pntxtb', tocPNTXTB);
          Add('pntxta', tocPNTXTA);
          Add('listtext', tocLISTTEXT);
          Add('ilvl', tocILVL);
          Add('pnrauth', tocPNRAUTH);
          Add('pnrdate', tocPNRDATE);
          Add('pnrnot', tocPNRNOT);
          Add('pnrxst', tocPNRXST);
          Add('pnrrgb', tocPNRRGB);
          Add('pnrpnbr', tocPNRPNBR);
          Add('pnrnfc', tocPNRNFC);
          Add('pnrstart', tocPNRSTART);
          Add('pnrstop', tocPNRSTOP);
          Add('dfrauth', tocDFRAUTH);
          Add('dfrdate', tocDFRDATE);
          Add('dfrxst', tocDFRXST);
          Add('dfrstart', tocDFRSTART);
          Add('dfrstop', tocDFRSTOP);
          Add('brdth', tocBRDTH);
          Add('shading', tocSHADING);
          Add('cfpat', tocCFPAT);
          Add('cbpat', tocCBPAT);
          Add('bghoriz', tocBGHORIZ);
          Add('bgvert', tocBGVERT);
          Add('bgfdiag', tocBGFDIAG);
          Add('bgbdiag', tocBGBDIAG);
          Add('bgcross', tocBGCROSS);
          Add('bgdcross', tocBGDCROSS);
          Add('bgdkhoriz', tocBGDKHORIZ);
          Add('bgdkvert', tocBGDKVERT);
          Add('bgdkfdiag', tocBGDKFDIAG);
          Add('bgdkbdiag', tocBGDKBDIAG);
          Add('bgdkcross', tocBGDKCROSS);
          Add('bgdkdcross', tocBGDKDCROSS);
          Add('absw', tocABSW);
          Add('absh', tocABSH);
          Add('nowrap', tocNOWRAP);
          Add('dxfrtext', tocDXFRTEXT);
          Add('dfrmtxtx', tocDFRMTXTX);
          Add('dfrmtxty', tocDFRMTXTY);
          Add('dropcapli', tocDROPCAPLI);
          Add('dropcapt', tocDROPCAPT);
          Add('phmrg', tocPHMRG);
          Add('phpg', tocPHPG);
          Add('phcol', tocPHCOL);
          Add('posx', tocPOSX);
          Add('posnegx', tocPOSNEGX);
          Add('posxc', tocPOSXC);
          Add('posxi', tocPOSXI);
          Add('posxo', tocPOSXO);
          Add('posxl', tocPOSXL);
          Add('posxr', tocPOSXR);
          Add('pvmrg', tocPVMRG);
          Add('pvpg', tocPVPG);
          Add('pvpara', tocPVPARA);
          Add('posy', tocPOSY);
          Add('posnegy', tocPOSNEGY);
          Add('posyt', tocPOSYT);
          Add('posyil', tocPOSYIL);
          Add('posyb', tocPOSYB);
          Add('posyc', tocPOSYC);
          Add('abslock', tocABSLOCK);
          Add('overlay', tocOVERLAY);
          Add('posyin', tocPOSYIN);
          Add('posyout', tocPOSYOUT);
          Add('dxfrtest', tocDXFRTEST);
          Add('trowd', tocTROWD);
          Add('trgaph', tocTRGAPH);
          Add('trleft', tocTRLEFT);
          Add('trrh', tocTRRH);
          Add('trhdr', tocTRHDR);
          Add('trkeep', tocTRKEEP);
          Add('trql', tocTRQL);
          Add('trqr', tocTRQR);
          Add('trqc', tocTRQC);
          Add('ltrrow', tocLTRROW);
          Add('rtlrow', tocRTLROW);
          Add('trbrdrt', tocTRBRDRT);
          Add('trbrdrl', tocTRBRDRL);
          Add('trbrdrb', tocTRBRDRB);
          Add('trbrdrr', tocTRBRDRR);
          Add('trbrdrh', tocTRBRDRH);
          Add('trbrdrv', tocTRBRDRV);
          Add('clmgf', tocCLMGF);
          Add('clmrg', tocCLMRG);
          Add('cellx', tocCELLX);
          Add('clbrdrt', tocCLBRDRT);
          Add('clbrdrl', tocCLBRDRL);
          Add('clbrdrb', tocCLBRDRB);
          Add('clbrdrr', tocCLBRDRR);
          Add('clcfpat', tocCLCFPAT);
          Add('clcbpat', tocCLCBPAT);
          Add('clshdng', tocCLSHDNG);
          Add('clbghoriz', tocCLBGHORIZ);
          Add('clbgvert', tocCLBGVERT);
          Add('clbgfdiag', tocCLBGFDIAG);
          Add('clbgbdiag', tocCLBGBDIAG);
          Add('clbgcross', tocCLBGCROSS);
          Add('clbgdcross', tocCLBGDCROSS);
          Add('clbgdkhor', tocCLBGDKHOR);
          Add('clbgdkvert', tocCLBGDKVERT);
          Add('clbgdkfdiag', tocCLBGDKFDIAG);
          Add('clbgdkbdiag', tocCLBGDKBDIAG);
          Add('clbgdkcross', tocCLBGDKCROSS);
          Add('clbgdkdcross', tocCLBGDKDCROSS);
          Add('cellxs', tocCELLXS);
          Add('cells', tocCELLS);
          Add('tcelld', tocTCELLD);
          Add('clvertalt', tocCLVERTALT);
          Add('clvertalc', tocCLVERTALC);
          Add('clvertalb', tocCLVERTALB);
          Add('cltxlrtb', tocCLTXLRTB);
          Add('cltxtbrl', tocCLTXTBRL);
          Add('clbrdr', tocCLBRDR);
          Add('b', tocB);
          Add('animtext', tocANIMTEXT);
          Add('caps', tocCAPS);
          Add('charscalex', tocCHARSCALEX);
          Add('deleted', tocDELETED);
          Add('dn', tocDN);
          Add('embo', tocEMBO);
          Add('impr', tocIMPR);
          Add('sub', tocSUB);
          Add('nosupersub', tocNOSUPERSUB);
          Add('expnd', tocEXPND);
          Add('expndtw', tocEXPNDTW);
          Add('kerning', tocKERNING);
          Add('i', tocI);
          Add('outl', tocOUTL);
          Add('scaps', tocSCAPS);
          Add('shad', tocSHAD);
          Add('strike', tocSTRIKE);
          Add('strikedl', tocSTRIKEDL);
          Add('ul', tocUL);
          Add('uld', tocULD);
          Add('uldash', tocULDASH);
          Add('uldashd', tocULDASHD);
          Add('uldashdd', tocULDASHDD);
          Add('uldb', tocULDB);
          Add('ulnone', tocULNONE);
          Add('ulth', tocULTH);
          Add('ulw', tocULW);
          Add('ulwave', tocULWAVE);
          Add('up', tocUP);
          Add('super', tocSUPER);
          Add('v', tocV);
          Add('rtlch', tocRTLCH);
          Add('ltrch', tocLTRCH);
          Add('cchs', tocCCHS);
          Add('lang', tocLANG);
          Add('chshdng', tocCHSHDNG);
          Add('chcfpat', tocCHCFPAT);
          Add('chcbpat', tocCHCBPAT);
          Add('chbghoriz', tocCHBGHORIZ);
          Add('chbgvert', tocCHBGVERT);
          Add('chbgfdiag', tocCHBGFDIAG);
          Add('chbgbdiag', tocCHBGBDIAG);
          Add('chbgcross', tocCHBGCROSS);
          Add('chbgdcross', tocCHBGDCROSS);
          Add('chbgdkhoriz', tocCHBGDKHORIZ);
          Add('chbgdkvert', tocCHBGDKVERT);
          Add('chbgdkfdiag', tocCHBGDKFDIAG);
          Add('chbgdkbdiag', tocCHBGDKBDIAG);
          Add('chbgdkcross', tocCHBGDKCROSS);
          Add('chbgdkdcross', tocCHBGDKDCROSS);
          Add('chbrdr', tocCHBRDR);
          Add('revised', tocREVISED);
          Add('revauth', tocREVAUTH);
          Add('revdttm', tocREVDTTM);
          Add('crauth', tocCRAUTH);
          Add('crdate', tocCRDATE);
          Add('revauthdel', tocREVAUTHDEL);
          Add('revdttmdel', tocREVDTTMDEL);
          Add('af', tocAF);
          Add('ab', tocAB);
          Add('au', tocAU);
          Add('ai', tocAI);
          Add('acaps', tocACAPS);
          Add('acf', tocACF);
          Add('adn', tocADN);
          Add('aexpnd', tocAEXPND);
          Add('afs', tocAFS);
          Add('alang', tocALANG);
          Add('aoutl', tocAOUTL);
          Add('ascaps', tocASCAPS);
          Add('ashad', tocASHAD);
          Add('astrike', tocASTRIKE);
          Add('aul', tocAUL);
          Add('auld', tocAULD);
          Add('auldb', tocAULDB);
          Add('aulnone', tocAULNONE);
          Add('aulw', tocAULW);
          Add('aup', tocAUP);
          Add('highlight', tocHIGHLIGHT);
          Add('chdate', tocCHDATE);
          Add('chdpl', tocCHDPL);
          Add('chdpa', tocCHDPA);
          Add('chtime', tocCHTIME);
          Add('chpgn', tocCHPGN);
          Add('sectnum', tocSECTNUM);
          Add('chftn', tocCHFTN);
          Add('chatn', tocCHATN);
          Add('chftnsep', tocCHFTNSEP);
          Add('chftnsepc', tocCHFTNSEPC);
          Add('page', tocPAGE);
          Add('column', tocCOLUMN);
          Add('line', tocLINE);
          Add('softpage', tocSOFTPAGE);
          Add('softcol', tocSOFTCOL);
          Add('softline', tocSOFTLINE);
          Add('softlheight', tocSOFTLHEIGHT);
          Add('tab', tocTAB);
          Add('emdash', tocEMDASH);
          Add('endash', tocENDASH);
          Add('emspace', tocEMSPACE);
          Add('enspace', tocENSPACE);
          Add('bullet', tocBULLET);
          Add('lquote', tocLQUOTE);
          Add('rquote', tocRQUOTE);
          Add('ldblquote', tocLDBLQUOTE);
          Add('rdblquote', tocRDBLQUOTE);
          Add('ltrmark', tocLTRMARK);
          Add('rtlmark', tocRTLMARK);
          Add('zwj', tocZWJ);
          Add('zwnj', tocZWNJ);
          Add('docvar', tocDOCVAR);
          Add('bkmkend', tocBKMKEND);
          Add('bkmkcolf', tocBKMKCOLF);
          Add('bkmkcoll', tocBKMKCOLL);
          Add('pict', tocPICT);
          Add('shppict', tocSHPPICT);
          Add('emfblip', tocEMFBLIP);
          Add('pngblip', tocPNGBLIP);
          Add('jpegblip', tocJPEGBLIP);
          Add('macpict', tocMACPICT);
          Add('pmmetafile', tocPMMETAFILE);
          Add('wmetafile', tocWMETAFILE);
          Add('dibitmap', tocDIBITMAP);
          Add('wbitmap', tocWBITMAP);
          Add('wbmbitspixel', tocWBMBITSPIXEL);
          Add('wbmplanes', tocWBMPLANES);
          Add('wbmwidthbytes', tocWBMWIDTHBYTES);
          Add('picw', tocPICW);
          Add('pich', tocPICH);
          Add('picwgoal', tocPICWGOAL);
          Add('pichgoal', tocPICHGOAL);
          Add('picscalex', tocPICSCALEX);
          Add('picscaley', tocPICSCALEY);
          Add('picscaled', tocPICSCALED);
          Add('piccropt', tocPICCROPT);
          Add('piccropb', tocPICCROPB);
          Add('piccropr', tocPICCROPR);
          Add('piccropl', tocPICCROPL);
          Add('picbmp', tocPICBMP);
          Add('picbpp', tocPICBPP);
          Add('bin', tocBIN);
          Add('nonshppict', tocNONSHPPICT);
          Add('picprop', tocPICPROP);
          Add('blipupi', tocBLIPUPI);
          Add('blipuid', tocBLIPUID);
          Add('bliptag', tocBLIPTAG);
          Add('object', tocOBJECT);
          Add('objemb', tocOBJEMB);
          Add('objlink', tocOBJLINK);
          Add('objautlink', tocOBJAUTLINK);
          Add('objsub', tocOBJSUB);
          Add('objpub', tocOBJPUB);
          Add('objicemb', tocOBJICEMB);
          Add('linkself', tocLINKSELF);
          Add('objlock', tocOBJLOCK);
          Add('objupdate', tocOBJUPDATE);
          Add('objclass', tocOBJCLASS);
          Add('objname', tocOBJNAME);
          Add('objtime', tocOBJTIME);
          Add('rsltmerge', tocRSLTMERGE);
          Add('rsltrtf', tocRSLTRTF);
          Add('rslttxt', tocRSLTTXT);
          Add('rsltpict', tocRSLTPICT);
          Add('rsltbmp', tocRSLTBMP);
          Add('objsetsize', tocOBJSETSIZE);
          Add('objalign', tocOBJALIGN);
          Add('objtransy', tocOBJTRANSY);
          Add('objcropt', tocOBJCROPT);
          Add('objcropb', tocOBJCROPB);
          Add('objcropl', tocOBJCROPL);
          Add('objcropr', tocOBJCROPR);
          Add('objscalex', tocOBJSCALEX);
          Add('objscaley', tocOBJSCALEY);
          Add('objh', tocOBJH);
          Add('objw', tocOBJW);
          Add('objdata', tocOBJDATA);
          Add('objalias', tocOBJALIAS);
          Add('objsect', tocOBJSECT);
          Add('result', tocRESULT);
          Add('objhtml', tocOBJHTML);
          Add('objocx', tocOBJOCX);
          Add('objattph', tocOBJATTPH);
          Add('bkmkpub', tocBKMKPUB);
          Add('pubauto', tocPUBAUTO);
          Add('do', tocDO);
          Add('dobxpage', tocDOBXPAGE);
          Add('dobxcolumn', tocDOBXCOLUMN);
          Add('dobxmargin', tocDOBXMARGIN);
          Add('dobypage', tocDOBYPAGE);
          Add('dobypara', tocDOBYPARA);
          Add('dobymargin', tocDOBYMARGIN);
          Add('dodhgt', tocDODHGT);
          Add('dolock', tocDOLOCK);
          Add('dpgroup', tocDPGROUP);
          Add('dpcount', tocDPCOUNT);
          Add('dpendgroup', tocDPENDGROUP);
          Add('dpcallout', tocDPCALLOUT);
          Add('dpcooffset', tocDPCOOFFSET);
          Add('dpcolength', tocDPCOLENGTH);
          Add('dpline', tocDPLINE);
          Add('dprect', tocDPRECT);
          Add('dproundr', tocDPROUNDR);
          Add('dptxbx', tocDPTXBX);
          Add('dptxbxmar', tocDPTXBXMAR);
          Add('dptxbxtext', tocDPTXBXTEXT);
          Add('dpellipse', tocDPELLIPSE);
          Add('dparc', tocDPARC);
          Add('dparcflipx', tocDPARCFLIPX);
          Add('dparcflipy', tocDPARCFLIPY);
          Add('dppolyline', tocDPPOLYLINE);
          Add('dppolygon', tocDPPOLYGON);
          Add('dppolycount', tocDPPOLYCOUNT);
          Add('dpptx', tocDPPTX);
          Add('dppty', tocDPPTY);
          Add('dpx', tocDPX);
          Add('dpy', tocDPY);
          Add('dpxsize', tocDPXSIZE);
          Add('dpysize', tocDPYSIZE);
          Add('dpcotright', tocDPCOTRIGHT);
          Add('dpcotsingle', tocDPCOTSINGLE);
          Add('dpcotdouble', tocDPCOTDOUBLE);
          Add('dpcottriple', tocDPCOTTRIPLE);
          Add('dpcoa', tocDPCOA);
          Add('dpcoaccent', tocDPCOACCENT);
          Add('dpcosmarta', tocDPCOSMARTA);
          Add('dpcobestfit', tocDPCOBESTFIT);
          Add('dpcominusx', tocDPCOMINUSX);
          Add('dpcominusy', tocDPCOMINUSY);
          Add('dpcoborder', tocDPCOBORDER);
          Add('dpcodtop', tocDPCODTOP);
          Add('dpcodcenter', tocDPCODCENTER);
          Add('dpcodbottom', tocDPCODBOTTOM);
          Add('dpcodabs', tocDPCODABS);
          Add('dplinew', tocDPLINEW);
          Add('dplinesolid', tocDPLINESOLID);
          Add('dplinehollow', tocDPLINEHOLLOW);
          Add('dplinedash', tocDPLINEDASH);
          Add('dplinedot', tocDPLINEDOT);
          Add('dplinedado', tocDPLINEDADO);
          Add('dplinedadodo', tocDPLINEDADODO);
          Add('dplinegray', tocDPLINEGRAY);
          Add('dplinecor', tocDPLINECOR);
          Add('dplinecog', tocDPLINECOG);
          Add('dplinecob', tocDPLINECOB);
          Add('dplinepal', tocDPLINEPAL);
          Add('dpfillpat', tocDPFILLPAT);
          Add('dpfillfggray', tocDPFILLFGGRAY);
          Add('dpfillfgcr', tocDPFILLFGCR);
          Add('dpfillfgcg', tocDPFILLFGCG);
          Add('dpfillfgcb', tocDPFILLFGCB);
          Add('dpfillfgpal', tocDPFILLFGPAL);
          Add('dpfillbggray', tocDPFILLBGGRAY);
          Add('dpfillbgcr', tocDPFILLBGCR);
          Add('dpfillbgcg', tocDPFILLBGCG);
          Add('dpfillbgcb', tocDPFILLBGCB);
          Add('dpfillbgpal', tocDPFILLBGPAL);
          Add('dpastartl', tocDPASTARTL);
          Add('dpastartw', tocDPASTARTW);
          Add('dpastartsol', tocDPASTARTSOL);
          Add('dpastarthol', tocDPASTARTHOL);
          Add('dpaendl', tocDPAENDL);
          Add('dpaendw', tocDPAENDW);
          Add('dpaendsol', tocDPAENDSOL);
          Add('dpaendhol', tocDPAENDHOL);
          Add('dpshadow', tocDPSHADOW);
          Add('dpshadx', tocDPSHADX);
          Add('dpshady', tocDPSHADY);
          Add('dpcodescent', tocDPCODESCENT);
          Add('shp', tocSHP);
          Add('shpinst', tocSHPINST);
          Add('spp', tocSPP);
          Add('sn', tocSN);
          Add('sp', tocSP);
          Add('shprslt', tocSHPRSLT);
          Add('shpleft', tocSHPLEFT);
          Add('shptop', tocSHPTOP);
          Add('shpbottom', tocSHPBOTTOM);
          Add('shpright', tocSHPRIGHT);
          Add('shplid', tocSHPLID);
          Add('shpz', tocSHPZ);
          Add('shpfhdr', tocSHPFHDR);
          Add('shpbxpage', tocSHPBXPAGE);
          Add('shpbxmargin', tocSHPBXMARGIN);
          Add('shpbxcolumn', tocSHPBXCOLUMN);
          Add('shpbypage', tocSHPBYPAGE);
          Add('shpbymargin', tocSHPBYMARGIN);
          Add('shpbypara', tocSHPBYPARA);
          Add('shpwr', tocSHPWR);
          Add('shpwrk', tocSHPWRK);
          Add('shpfblwtxt', tocSHPFBLWTXT);
          Add('shplockanchor', tocSHPLOCKANCHOR);
          Add('shptxt', tocSHPTXT);
          Add('shpgrp', tocSHPGRP);
          Add('background', tocBACKGROUND);
          Add('sv', tocSV);
          Add('hl', tocHL);
          Add('hlloc', tocHLLOC);
          Add('hlsrc', tocHLSRC);
          Add('hlfr', tocHLFR);
          Add('footnote', tocFOOTNOTE);
          Add('pu', tocPU);
          Add('ftnalt', tocFTNALT);
          Add('atnid', tocATNID);
          Add('annotation', tocANNOTATION);
          Add('atrfstart', tocATRFSTART);
          Add('atrfend', tocATRFEND);
          Add('atnauthor', tocATNAUTHOR);
          Add('atnref', tocATNREF);
          Add('atntime', tocATNTIME);
          Add('atnicn', tocATNICN);
          Add('field', tocFIELD);
          Add('fldinst', tocFLDINST);
          Add('fldrslt', tocFLDRSLT);
          Add('flddirty', tocFLDDIRTY);
          Add('fldedit', tocFLDEDIT);
          Add('fldlock', tocFLDLOCK);
          Add('fldpriv', tocFLDPRIV);
          Add('fldalt', tocFLDALT);
          Add('datafield', tocDATAFIELD);
          Add('fldtype', tocFLDTYPE);
          Add('date', tocDATE);
          Add('time', tocTIME);
          Add('wpeqn', tocWPEQN);
          Add('formfield', tocFORMFIELD);
          Add('fftype', tocFFTYPE);
          Add('ffownhelp', tocFFOWNHELP);
          Add('ffhelptext', tocFFHELPTEXT);
          Add('ffownstat', tocFFOWNSTAT);
          Add('ffstattext', tocFFSTATTEXT);
          Add('ffprot', tocFFPROT);
          Add('ffsize', tocFFSIZE);
          Add('fftypetxt', tocFFTYPETXT);
          Add('ffrecalc', tocFFRECALC);
          Add('ffhaslistbox', tocFFHASLISTBOX);
          Add('ffmaxlen', tocFFMAXLEN);
          Add('ffhps', tocFFHPS);
          Add('ffname', tocFFNAME);
          Add('ffdeftext', tocFFDEFTEXT);
          Add('ffdefres', tocFFDEFRES);
          Add('ffformat', tocFFFORMAT);
          Add('ffentrymcr', tocFFENTRYMCR);
          Add('ffexitmcr', tocFFEXITMCR);
          Add('ffl', tocFFL);
          Add('ffres', tocFFRES);
          Add('xe', tocXE);
          Add('xef', tocXEF);
          Add('bxe', tocBXE);
          Add('ixe', tocIXE);
          Add('txe', tocTXE);
          Add('rxe', tocRXE);
          Add('tc', tocTC);
          Add('tcn', tocTCN);
          Add('tcf', tocTCF);
          Add('tcl', tocTCL);
        end;
     end;
end;

initialization

finalization
  FreeAndNil(RTFLookupTable);
end.
